In [6]:
import numpy as np
import pandas as pd
import os
import sys
import re
import wfdb
import scipy.stats as stats
from scipy.fft import fft, fftfreq

In [7]:
2048*5

10240

In [2]:
def extract_unique_values_from_folder(folder:str):
    """
    Function to extract just the unique headers of the dat and hea files (removing the file name) 
    """
    unique = set()
    for f in os.listdir(folder):
        unique.add(extract_basename(os.path.join(folder, f)))
        
    return list(unique)

In [3]:
def extract_basename(filename):
    """
    Function to extract just the unique headers of the dat and hea files (removing the file spec) 
    """
    return os.path.splitext(filename)[0]

In [4]:
def extract_info_from_name(filename):
    parsed = {}
    basename = os.path.basename(filename).split(".")[0]
    pattern = r"session(\d+)_participant(\d+)_gesture(\d+)_trial(\d+)"
    match = re.match(pattern, basename)
    parsed['session'] = match.group(1) 
    parsed['participant'] = match.group(2)
    parsed['gesture'] = match.group(3) 
    parsed['trial'] = match.group(4)
    parsed['filename'] = filename
    return parsed

In [5]:
base_path = "../../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/"

In [8]:
chunk_lens={
    "1s": int(10240 / 5),
    "500ms": int(10240 / 10),
    "250ms": int(10240 / 20)
}

In [72]:
session1 = os.path.abspath(base_path+"Session1")
session2 = os.path.abspath(base_path+"Session2")
session3 = os.path.abspath(base_path+"Session3")
unique_values = extract_unique_values_from_folder(session1)

parsed_data_1 = []
parsed_data_2 = []
parsed_data_3 = []

for participant_dir in os.listdir(session1):
    participant_path = os.path.join(session1, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_1.append(extract_info_from_name(file_path))

for participant_dir in os.listdir(session2):
    participant_path = os.path.join(session2, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_2.append(extract_info_from_name(file_path))

for participant_dir in os.listdir(session3):
    participant_path = os.path.join(session3, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_3.append(extract_info_from_name(file_path))

#parsed_data
df1 = pd.DataFrame(parsed_data_1)
df2 = pd.DataFrame(parsed_data_2)
df3 = pd.DataFrame(parsed_data_3)

df = pd.concat([df1, df2, df3], axis=0)
# df = df1.iloc[:10, :]
df['filename'] = df['filename'].str.replace('.hea', '')
df

C:\Users\tanma\AppData\Local\Temp\ipykernel_26692\2860067031.py:47: FutureWarning: The default value of regex will change from True to False in a future version.
  df['filename'] = df['filename'].str.replace('.hea', '')


session participant gesture trial  \
0          1           1      10     1   
1          1           1      10     2   
2          1           1      10     3   
3          1           1      10     4   
4          1           1      10     5   
...      ...         ...     ...   ...   
5112       3           9       9     3   
5113       3           9       9     4   
5114       3           9       9     5   
5115       3           9       9     6   
5116       3           9       9     7   

                                               filename  
0     E:\DS5500-project\data\gesture-recognition-and...  
1     E:\DS5500-project\data\gesture-recognition-and...  
2     E:\DS5500-project\data\gesture-recognition-and...  
3     E:\DS5500-project\data\gesture-recognition-and...  
4     E:\DS5500-project\data\gesture-recognition-and...  
...                                                 ...  
5112  E:\DS5500-project\data\gesture-recognition-and...  
5113  E:\DS5500-project\data\gesture-recognition-and...  
5114  E:\DS5500-project\data\gesture-recognition-and...  
5115  E:\DS5500-project\data\gesture-recognition-and...  
5116  E:\DS5500-project\data\gesture-recognition-and...  

[15351 rows x 5 columns]

In [73]:
chunk_lens['250ms']

512

In [59]:
# df['trial'].unique()

In [60]:
# df['participant'].unique()

In [61]:

# def integrated_EMG(signal):
#     return np.sum(np.abs(signal))

# def mean_absolute_value(signal):
#     return np.mean(np.abs(signal))

# def simple_square_integral(signal):
#     return np.sum(signal**2)

# def root_mean_square(signal):
#     return np.sqrt(np.mean(signal**2))

# def variance(signal):
#     return np.var(signal)

# def myopulse_percentage_rate(signal):
#     return len(np.where(np.diff(np.sign(signal)))[0]) / len(signal)

# def waveform_length(signal):
#     return np.sum(np.abs(np.diff(signal)))

# def difference_variance(signal):
#     return np.var(np.diff(signal))

# def difference_absolute_standard_deviation(signal):
#     return np.std(np.diff(np.abs(signal)))

# def willison_amplitude(signal, threshold=0.1):
#     return np.sum(np.abs(np.diff(signal)) > threshold)

In [16]:
t = np.random.randn(10,4)

th = np.mean(t, axis = 0) + 3 * np.std(t, axis = 0)

In [17]:
t[3:7, :]

array([[ 0.97925754,  0.64199681, -0.52724884,  1.10391008],
       [ 0.18798038,  0.45601919,  0.28672318,  0.9877338 ],
       [-0.3155312 ,  0.61305269, -1.10797285,  0.37430956],
       [ 1.91413559,  0.72953631, -1.18700305, -1.81200469]])

In [123]:
th

array([3.53320721, 3.82634451, 3.23082561, 1.6049687 ])

In [124]:
np.mean(t, axis = 0)

array([ 0.1260221 ,  0.11618935,  0.78446029, -0.4030366 ])

In [125]:
 np.sum(t**2, axis=0)

array([13.05760502, 15.42972331, 12.80344981,  6.10447978])

In [126]:
np.mean(t, axis = 0)

array([ 0.1260221 ,  0.11618935,  0.78446029, -0.4030366 ])

In [127]:
np.std(t, axis = 0)

array([1.13572837, 1.23671839, 0.8154551 , 0.6693351 ])

In [128]:
th

array([3.53320721, 3.82634451, 3.23082561, 1.6049687 ])

In [129]:
np.sum(np.abs(np.diff(t, axis = 0)) > th, axis = 0)

array([0, 0, 0, 0])

In [130]:
np.diff(t, axis = 0)

array([[ 2.99335433, -3.45811759,  0.26152882,  0.24160798],
       [-2.34207696,  2.35791158,  1.56628613, -0.24404068],
       [ 0.36437501, -3.22662996, -0.1890656 , -1.14076241],
       [ 0.14327592,  3.17231789,  0.93899233,  0.71616219],
       [-0.37651959,  0.05651657, -0.56747082,  0.25337814],
       [-2.31498092, -1.71324716, -0.18585936, -1.42222018],
       [ 2.53359462,  0.0922157 ,  0.44544493,  1.21581115],
       [-1.37045244,  0.90993165, -0.59303695,  1.33051117],
       [ 0.15225351, -0.74953327, -0.94581912, -1.37692946]])

In [134]:
cols = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11',
       'F12', 'F13', 'F14', 'F15', 'F16', 'W1', 'W2', 'W3', 'W4', 'W5', 'W6',
       'W7', 'W8', 'W9', 'W10', 'W11', 'W12']

In [62]:
def extract_features(df, chunk = False, chunk_lens = None):
    """
    Extracting the following features:
    'MIN','MAX','MEAN','RMS','VAR','STD','POWER','PEAK','P2P','CREST FACTOR','SKEW','KURTOSIS',
            'MAX_f','SUM_f','MEAN_f','VAR_f','PEAK_f','SKEW_f','KURTOSIS_f'
    These will be an array of values for each of the 32 sensors
    """
    #time data
    features = {}
    #time domain features
    if chunk:
        time_data = df.values[2048: 2048 + chunk_lens, :]
    else:
        time_data = df.values
    #Three std seems excessive. This can be changed later
    th = np.mean(time_data, axis = 0) + 2 * np.std(time_data, axis = 0)
    features['iemg'] = np.sum(np.abs(time_data), axis=0)
    features['mav'] = np.mean(np.abs(time_data), axis=0)
    features['ssi'] = np.sum(time_data**2, axis=0)
    # features['myopulse'] = len(np.where(np.diff(np.sign(time_data)))[0]) / len(time_data)
    #ref = https://github.com/tanmaygadgil/DS5500-project/blob/main/code_snippets/python-sebastian/feature_extraction.py
    features['myopulse'] = np.sum(time_data >= th, axis = 0) / len(time_data)
    features['wflen'] = np.sum(np.abs(np.diff(time_data, axis = 0)), axis=0)
    features['diffvar'] = np.var(np.diff(time_data, axis = 0), axis = 0)
    features['dasd'] = np.std(np.diff(np.abs(time_data), axis = 0), axis = 0)
    #Ref #ref = https://github.com/tanmaygadgil/DS5500-project/blob/main/code_snippets/python-sebastian/feature_extraction.py
    features['willison'] = np.sum(np.abs(np.diff(time_data, axis = 0)) > th, axis = 0)
    
    features['mean'] = np.mean(time_data, axis = 0)
    features['min'] = np.min(time_data, axis = 0)
    features['max'] = np.max(time_data, axis = 0)
    features['rms'] = np.sqrt(np.mean(time_data**2, axis = 0))
    features['max'] = np.std(time_data, axis = 0)
    features['power'] = np.mean(time_data**2, axis = 0)
    features['peak'] = np.max(np.abs(time_data), axis = 0)
    features['p2p'] = np.ptp(time_data, axis = 0)
    features['crest_factor'] = np.max(np.abs(time_data), axis = 0)/np.sqrt(np.mean(time_data**2, axis = 0))
    features['skew'] = stats.skew(time_data, axis = 0)
    features['kurtosis'] = stats.kurtosis(time_data, axis = 0)
    features['form_factor'] =np.sqrt(np.mean(time_data**2, axis = 0)) / np.mean(time_data, axis = 0)
    features['pulse_indicator'] = np.max(np.abs(time_data), axis = 0)/np.mean(time_data, axis = 0) 
    
    #Convert to frequency domain
    freq_data = fft(time_data)
    S_f = np.abs(freq_data**2)/len(df)
    features['max_f'] = np.max(S_f, axis = 0)
    features['sum_f'] = np.sum(S_f, axis = 0)
    features['mean_f'] = np.mean(S_f, axis = 0)
    features['var_f'] = np.var(S_f, axis = 0)
    features['peak_f'] = np.max(np.abs(S_f), axis = 0)
    features['skew_f'] = stats.skew(S_f, axis = 0)
    features['kurtosis_f'] = stats.kurtosis(S_f, axis = 0)
    
    return features
    

In [34]:
from tqdm import tqdm

In [35]:
wave = wfdb.rdrecord(df['filename'].iloc[0])
wave_df = wave.to_dataframe()
wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)

In [36]:
wave_df

F1        F2        F3        F4        F5  \
0 days 00:00:00            0.018842  0.003025  0.046460  0.104214  0.078568   
0 days 00:00:00.000488281  0.007086 -0.007874  0.004497  0.054350 -0.043084   
0 days 00:00:00.000976562 -0.018860 -0.037642 -0.040174 -0.003930 -0.175231   
0 days 00:00:00.001464843 -0.013056 -0.036159 -0.049285 -0.019746 -0.233636   
0 days 00:00:00.001953124  0.025837  0.006250 -0.017654  0.013535 -0.205318   
...                             ...       ...       ...       ...       ...   
0 days 00:00:04.997556035 -0.046034 -0.075884 -0.073877 -0.076665 -0.115671   
0 days 00:00:04.998044316 -0.016398 -0.042997 -0.033536 -0.052874 -0.050325   
0 days 00:00:04.998532597  0.001108 -0.024600 -0.008593 -0.027242 -0.008290   
0 days 00:00:04.999020878  0.003021 -0.018727 -0.003628 -0.012806 -0.012712   
0 days 00:00:04.999509159 -0.002728 -0.012182 -0.004230 -0.013803 -0.033760   

                                 F6        F7        F8        F9       F10  \
0 days 00:00:00            0.139992  0.093088  0.033105  0.003268 -0.046261   
0 days 00:00:00.000488281  0.000402  0.053829  0.018269  0.013704 -0.032529   
0 days 00:00:00.000976562 -0.169030 -0.003461 -0.003630 -0.009620 -0.050602   
0 days 00:00:00.001464843 -0.278486 -0.028711 -0.003322 -0.020864 -0.047258   
0 days 00:00:00.001953124 -0.291812 -0.012940  0.019870  0.004719 -0.003508   
...                             ...       ...       ...       ...       ...   
0 days 00:00:04.997556035 -0.118026 -0.048888 -0.043507 -0.046553 -0.068948   
0 days 00:00:04.998044316 -0.047177 -0.006694 -0.010307 -0.014983 -0.036733   
0 days 00:00:04.998532597 -0.007932  0.023454  0.010110 -0.000144 -0.024079   
0 days 00:00:04.999020878 -0.004160  0.032820  0.016069 -0.001028 -0.023260   
0 days 00:00:04.999509159 -0.012037  0.025776  0.013484 -0.005709 -0.017404   

                           ...        W3        W4        W5        W6  \
0 days 00:00:00            ...  0.013156 -0.041120 -0.085215  0.001288   
0 days 00:00:00.000488281  ... -0.021570 -0.043785 -0.120230 -0.029939   
0 days 00:00:00.000976562  ... -0.032417 -0.050653 -0.124954 -0.034229   
0 days 00:00:00.001464843  ... -0.024087 -0.049352 -0.109183 -0.034107   
0 days 00:00:00.001953124  ... -0.002855 -0.024827 -0.082030 -0.039545   
...                        ...       ...       ...       ...       ...   
0 days 00:00:04.997556035  ... -0.006198 -0.006975  0.028131  0.032132   
0 days 00:00:04.998044316  ... -0.006423 -0.009028  0.035122  0.045688   
0 days 00:00:04.998532597  ... -0.005212 -0.002708  0.042888  0.058652   
0 days 00:00:04.999020878  ...  0.001042  0.006685  0.045966  0.057129   
0 days 00:00:04.999509159  ...  0.010903  0.012682  0.041373  0.042895   

                                 W7        W8        W9       W10       W11  \
0 days 00:00:00            0.099477  0.077323  0.006146 -0.032260 -0.080570   
0 days 00:00:00.000488281  0.118181  0.076367 -0.011716 -0.036650 -0.117002   
0 days 00:00:00.000976562  0.126799  0.077234 -0.018928 -0.040363 -0.123522   
0 days 00:00:00.001464843  0.109105  0.067106 -0.017590 -0.037744 -0.108100   
0 days 00:00:00.001953124  0.057957  0.042862 -0.012414 -0.026509 -0.081828   
...                             ...       ...       ...       ...       ...   
0 days 00:00:04.997556035 -0.009935  0.007103 -0.004418 -0.006439  0.023369   
0 days 00:00:04.998044316  0.011053  0.014663 -0.002744 -0.001974  0.031485   
0 days 00:00:04.998532597  0.023663  0.012143 -0.002599  0.002870  0.042420   
0 days 00:00:04.999020878  0.017105  0.003124 -0.002948  0.004054  0.047149   
0 days 00:00:04.999509159  0.004568  0.000278 -0.002191  0.002454  0.041754   

                                W12  
0 days 00:00:00            0.010847  
0 days 00:00:00.000488281 -0.010532  
0 days 00:00:00.000976562 -0.021235  
0 days 00:00:00.001464843 -0.025145  
0 days 00:00:00.001953124 -0.032091  
...                             ...  
0 days 00:00:04.997556035  0.01

In [37]:
cols = wave_df.columns

In [38]:
cols

Index(['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11',
       'F12', 'F13', 'F14', 'F15', 'F16', 'W1', 'W2', 'W3', 'W4', 'W5', 'W6',
       'W7', 'W8', 'W9', 'W10', 'W11', 'W12'],
      dtype='object')

In [39]:
a = pd.DataFrame(f, index=cols)

In [40]:
a = a.unstack().to_frame().sort_index(level=1).T

In [41]:
a.columns

MultiIndex([(   'crest_factor', 'F1'),
            (           'dasd', 'F1'),
            (        'diffvar', 'F1'),
            (    'form_factor', 'F1'),
            (           'iemg', 'F1'),
            (       'kurtosis', 'F1'),
            (     'kurtosis_f', 'F1'),
            (            'mav', 'F1'),
            (            'max', 'F1'),
            (          'max_f', 'F1'),
            ...
            (          'power', 'W9'),
            ('pulse_indicator', 'W9'),
            (            'rms', 'W9'),
            (           'skew', 'W9'),
            (         'skew_f', 'W9'),
            (            'ssi', 'W9'),
            (          'sum_f', 'W9'),
            (          'var_f', 'W9'),
            (          'wflen', 'W9'),
            (       'willison', 'W9')],
           length=756)

In [42]:
a.columns = a.columns.map('_'.join)

In [43]:
a

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0         4.950507  0.050075    0.003132   -53607.972529  941.080017   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...  power_W9  \
0     1.469007      29.758598  0.091902  0.122266  0.014425  ...  0.000996   

   pulse_indicator_W9    rms_W9  skew_W9  skew_f_W9     ssi_W9  sum_f_W9  \
0       -26268.045653  0.031556 -0.00028   4.730823  10.196812  0.286288   

       var_f_W9    wflen_W9  willison_W9  
0  2.015109e-09  114.999665         12.0  

[1 rows x 756 columns]

In [44]:
temp

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0         4.950507  0.050075    0.003132   -53607.972529  941.080017   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0     1.469007      29.758598  0.091902  0.122266  0.014425  ...  0.031556   

   skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9    wflen_W9  \
0 -0.00028   4.730823  10.196812  0.286288  2.015109e-09  114.999665   

   willison_W9  gesture  participant  
0         12.0       11            1  

[1 rows x 758 columns]

In [64]:
chunk_lens['500ms']

1024

In [74]:
df_list = []
for i in tqdm(range(len(df))):
    wave = wfdb.rdrecord(df['filename'].iloc[i])
    wave_df = wave.to_dataframe()
    wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
    f = extract_features(wave_df, chunk=True, chunk_lens=chunk_lens['250ms'])
    temp = pd.DataFrame(f, index=cols)
    temp = temp.unstack().to_frame().sort_index(level=1).T
    temp.columns = temp.columns.map('_'.join)
    temp['gesture'] = df['gesture'].iloc[i]
    temp['participant'] = df['participant'].iloc[i]

    # e = pd.DataFrame.from_dict(temp, orient='index').T
    # new_df = pd.concat([new_df, temp])
    df_list.append(temp)

new_df = pd.concat(df_list)

new_df

100%|████████████████████████████████████████████████████████████████████████████| 15351/15351 [12:02<00:00, 21.25it/s]


crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1    iemg_F1  \
0          3.963505  0.025410    0.000813     -289.344418  21.112081   
0          3.671088  0.021105    0.000555     -106.425561  17.831058   
0          4.612221  0.021962    0.000596       31.279275  21.576849   
0          3.596929  0.059542    0.004202     -101.810923  60.856905   
0          3.369614  0.030592    0.001276      678.680596  27.068893   
..              ...       ...         ...             ...        ...   
0          3.550602  0.011181    0.000143     -935.693167  12.848445   
0          3.198854  0.018045    0.000389       89.805074  19.082627   
0          3.496704  0.022217    0.000586      -65.838778  22.905369   
0          3.869880  0.016193    0.000319     -327.538075  17.700126   
0          5.505573  0.020028    0.000453       49.349658  18.496744   

    kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0      0.919159      31.334996  0.041235  0.052909  0.002124  ...  0.029079   
0      0.375778      10.495107  0.034826  0.044259  0.000783  ...  0.016885   
0      2.312412      21.682307  0.042142  0.056349  0.001868  ...  0.022612   
0      1.330189       9.403929  0.118861  0.160457  0.010985  ...  0.037485   
0      0.023663       3.475985  0.052869  0.065866  0.001219  ...  0.032975   
..          ...            ...       ...       ...       ...  ...       ...   
0      0.753193       5.701307  0.025095  0.032303  0.000269  ...  0.020591   
0      0.246325       8.584008  0.037271  0.047385  0.000648  ...  0.028650   
0      0.839749       5.800207  0.044737  0.058507  0.000774  ...  0.039886   
0      1.099209      29.351911  0.034571  0.046015  0.000632  ...  0.015737   
0      3.998320      15.428954  0.036126  0.049865  0.000792  ...  0.020040   

     skew_W9  skew_f_W9    ssi_W9  sum_f_W9      var_f_W9  wflen_W9  \
0   0.072222   2.511020  0.432939  0.008130  3.964793e-10  4.738240   
0  -0.327373   3.008486  0.145968  0.003315  5.777674e-11  2.905545   
0  -0.685085   6.404526  0.261796  0.007892  7.770187e-10  3.681110   
0   0.048006   2.158654  0.719406  0.019679  1.856085e-09  5.631111   
0   0.239004   3.239978  0.556730  0.013197  1.026835e-09  5.653857   
..       ...        ...       ...       ...           ...       ...   
0   0.284598   2.564642  0.217072  0.001398  1.094183e-11  2.012504   
0  -0.102584   4.378273  0.420250  0.004425  1.455809e-10  2.996039   
0  -0.401008   3.533121  0.814526  0.004930  1.681511e-10  3.741230   
0  -0.772348   2.338708  0.126796  0.003617  6.669930e-11  1.957923   
0  -0.095961   3.440249  0.205623  0.004516  1.158276e-10  2.407260   

    willison_W9  gesture  participant  
0           0.0       10            1  
0           2.0       10            1  
0           0.0       10            1  
0           0.0       10            1  
0           0.0       10            1  
..          ...      ...          ...  
0           0.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           0.0        9            9  

[15351 rows x 758 columns]

In [46]:
new_df

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0         4.941577  0.021858    0.000602     1037.599009   75.484859   
0         4.015133  0.018487    0.000435     -211.949271   64.240456   
0         5.049360  0.020290    0.000502      140.799466   78.418150   
0         5.183690  0.042173    0.002158    -1848.393926  164.005595   
0         3.755162  0.026213    0.000885      722.556646   95.661511   
0         6.420748  0.020368    0.000508     -237.094776   64.395154   
0         5.409194  0.028676    0.001014     -229.117675  113.468596   
0         5.643077  0.062683    0.004812     -201.430915  263.814659   
0         4.602670  0.059257    0.004298    -1389.115519  223.629916   
0         3.820000  0.055743    0.003815      142.926148  210.540135   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0     1.067706      34.849548  0.036858  0.047656  0.002124  ...  0.024065   
0     0.484096      11.318800  0.031367  0.040468  0.000783  ...  0.014639   
0     2.150555      34.386343  0.038290  0.051495  0.002541  ...  0.020120   
0     3.042214      29.339296  0.080081  0.111346  0.010985  ...  0.036762   
0     0.281911       8.134258  0.046710  0.059104  0.001593  ...  0.031955   
0     8.238060      84.441085  0.031443  0.055951  0.008846  ...  0.024259   
0     1.769201      34.043712  0.055405  0.072408  0.005416  ...  0.048433   
0     2.987450      62.415114  0.128816  0.176129  0.040537  ...  0.035120   
0     1.949004      25.219872  0.109194  0.147377  0.016279  ...  0.032040   
0     0.969689      17.359746  0.102803  0.135671  0.011989  ...  0.037194   

    skew_W9  skew_f_W9    ssi_W9  sum_f_W9      var_f_W9   wflen_W9  \
0  0.058545   2.750350  1.186041  0.027343  2.566220e-10  16.109842   
0 -0.265784   3.000759  0.438884  0.010806  3.993698e-11  10.622426   
0 -0.298060   6.462532  0.829099  0.023183  4.037725e-10  13.897530   
0 -0.239751   3.546020  2.767716  0.054323  1.131449e-09  21.706093   
0  0.047708   3.409142  2.091314  0.037705  5.789632e-10  20.312315   
0 -0.655962   6.560225  1.205224  0.025890  1.448506e-09  10.704960   
0 -0.018325   4.043725  4.804121  0.051569  1.204357e-09  24.933637   
0  0.448072   4.523053  2.526073  0.105505  7.475943e-09  23.045996   
0  0.145919   5.056861  2.102429  0.081990  4.624972e-09  24.585065   
0 -0.071780   3.819345  2.833189  0.080597  3.555686e-09  27.634471   

   willison_W9  gesture  participant  
0          0.0       10            1  
0          4.0       10            1  
0          4.0       10            1  
0          0.0       10            1  
0          0.0       10            1  
0          1.0       10            1  
0          0.0       10            1  
0          4.0       11            1  
0          1.0       11            1  
0          2.0       11            1  

[10 rows x 758 columns]

In [138]:
new_df.reset_index()

index  crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1  \
0          0         7.091099  0.021834    0.000606    -6502.754507   
1          0        13.324514  0.023852    0.000689     1352.897349   
2          0         8.047954  0.016213    0.000326     1295.052394   
3          0         8.459555  0.026572    0.000864    14453.068135   
4          0         8.329011  0.026896    0.000901    11827.310277   
...      ...              ...       ...         ...             ...   
15346      0         7.771453  0.013208    0.000208     2599.892725   
15347      0         9.172642  0.019135    0.000429     1255.242161   
15348      0         5.923115  0.018533    0.000408     1713.228290   
15349      0         6.466362  0.015749    0.000292     -992.810528   
15350      0         6.331101  0.016365    0.000319     2571.088691   

          iemg_F1  kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  ...  \
0      365.456658     2.574033      85.547962  0.035689  0.047925  ...   
1      379.664639    16.942218     329.114870  0.037077  0.057235  ...   
2      296.823135     3.795827     134.751765  0.028987  0.039620  ...   
3      479.688214     6.938354      98.832790  0.046845  0.068228  ...   
4      464.350257     2.379207     116.412205  0.045347  0.060540  ...   
...           ...          ...            ...       ...       ...  ...   
15346  274.024844     2.176596      28.888640  0.026760  0.035561  ...   
15347  385.695263     4.615531     133.237150  0.037666  0.051690  ...   
15348  389.039490     1.912226      22.613382  0.037992  0.050501  ...   
15349  319.503197     2.189195      21.864578  0.031201  0.041789  ...   
15350  335.584187     1.845409      28.544842  0.032772  0.043372  ...   

         rms_W9   skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9  \
0      0.022588 -0.148877   5.529415   5.224663  0.109574  2.901826e-10   
1      0.016172 -0.205427   9.332349   2.677940  0.077566  2.769772e-10   
2      0.017039 -0.204604   9.078430   2.973002  0.064458  1.426359e-10   
3      0.031982 -0.266818   5.067522  10.473811  0.131909  4.509337e-10   
4      0.031134 -0.092205   5.414199   9.925787  0.177516  9.577100e-10   
...         ...       ...        ...        ...       ...           ...   
15346  0.020526 -0.293608   3.830298   4.314177  0.035283  1.966555e-11   
15347  0.025825 -0.389927   4.200155   6.829604  0.076162  1.003953e-10   
15348  0.027460 -0.321020   4.375813   7.721463  0.081006  1.125954e-10   
15349  0.013359 -0.493375   3.832319   1.827333  0.062739  6.332731e-11   
15350  0.015422 -0.457244   3.590272   2.435599  0.071311  7.882752e-11   

        wflen_W9  willison_W9  gesture  participant  
0      69.944068         15.0       10            1  
1      54.530919         23.0       10            1  
2      57.815909         13.0       10            1  
3      83.441138          0.0       10            1  
4      94.393506          3.0       10            1  
...          ...          ...      ...          ...  
15346  40.970398          2.0        9            9  
15347  52.342457          0.0        9            9  
15348  59.843660          0.0        9            9  
15349  35.905471          0.0        9            9  
15350  40.497393          4.0        9            9  

[15351 rows x 759 columns]

In [75]:
new_df.reset_index(inplace=True, drop=True)

In [50]:
new_df.head(10)

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0         4.941577  0.021858    0.000602     1037.599009   75.484859   
1         4.015133  0.018487    0.000435     -211.949271   64.240456   
2         5.049360  0.020290    0.000502      140.799466   78.418150   
3         5.183690  0.042173    0.002158    -1848.393926  164.005595   
4         3.755162  0.026213    0.000885      722.556646   95.661511   
5         6.420748  0.020368    0.000508     -237.094776   64.395154   
6         5.409194  0.028676    0.001014     -229.117675  113.468596   
7         5.643077  0.062683    0.004812     -201.430915  263.814659   
8         4.602670  0.059257    0.004298    -1389.115519  223.629916   
9         3.820000  0.055743    0.003815      142.926148  210.540135   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0     1.067706      34.849548  0.036858  0.047656  0.002124  ...  0.024065   
1     0.484096      11.318800  0.031367  0.040468  0.000783  ...  0.014639   
2     2.150555      34.386343  0.038290  0.051495  0.002541  ...  0.020120   
3     3.042214      29.339296  0.080081  0.111346  0.010985  ...  0.036762   
4     0.281911       8.134258  0.046710  0.059104  0.001593  ...  0.031955   
5     8.238060      84.441085  0.031443  0.055951  0.008846  ...  0.024259   
6     1.769201      34.043712  0.055405  0.072408  0.005416  ...  0.048433   
7     2.987450      62.415114  0.128816  0.176129  0.040537  ...  0.035120   
8     1.949004      25.219872  0.109194  0.147377  0.016279  ...  0.032040   
9     0.969689      17.359746  0.102803  0.135671  0.011989  ...  0.037194   

    skew_W9  skew_f_W9    ssi_W9  sum_f_W9      var_f_W9   wflen_W9  \
0  0.058545   2.750350  1.186041  0.027343  2.566220e-10  16.109842   
1 -0.265784   3.000759  0.438884  0.010806  3.993698e-11  10.622426   
2 -0.298060   6.462532  0.829099  0.023183  4.037725e-10  13.897530   
3 -0.239751   3.546020  2.767716  0.054323  1.131449e-09  21.706093   
4  0.047708   3.409142  2.091314  0.037705  5.789632e-10  20.312315   
5 -0.655962   6.560225  1.205224  0.025890  1.448506e-09  10.704960   
6 -0.018325   4.043725  4.804121  0.051569  1.204357e-09  24.933637   
7  0.448072   4.523053  2.526073  0.105505  7.475943e-09  23.045996   
8  0.145919   5.056861  2.102429  0.081990  4.624972e-09  24.585065   
9 -0.071780   3.819345  2.833189  0.080597  3.555686e-09  27.634471   

   willison_W9  gesture  participant  
0          0.0       10            1  
1          4.0       10            1  
2          4.0       10            1  
3          0.0       10            1  
4          0.0       10            1  
5          1.0       10            1  
6          0.0       10            1  
7          4.0       11            1  
8          1.0       11            1  
9          2.0       11            1  

[10 rows x 758 columns]

In [51]:
# new_df1 = pd.DataFrame()
# for i in range(10):
#     wave = wfdb.rdrecord(df['filename'].iloc[i])
#     wave_df = wave.to_dataframe()
#     wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
#     f = extract_features(wave_df)
#     f['gesture'] = df['gesture'].iloc[i]
#     f['participant'] = df['participant'].iloc[i]

#     e = pd.DataFrame.from_dict(f, orient='index').T
#     new_df1 = new_df1.append(e, ignore_index = False)

# new_df1.reset_index()

In [139]:
new_df.reset_index(drop=True).to_csv(base_path+"features_v2.csv", index = False)

In [371]:
# i = 53
# wave = wfdb.rdrecord(df['filename'].iloc[i])
# wave_df = wave.to_dataframe()
# wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
# f = extract_features(wave_df)
# f['gesture'] = df['gesture'].iloc[i]
# f['participant'] = df['participant'].iloc[i]

# g = pd.DataFrame.from_dict(f, orient='index').T

# # new_df = pd.DataFrame(columns = ['iemg', 'mav', 'ssi', 'myopulse', 'wflen', 'diffvar', 'dasd',
# #        'willison', 'mean', 'min', 'max', 'rms', 'power', 'peak', 'p2p',
# #        'crest_factor', 'skew', 'kurtosis', 'form_factor', 'pulse_indicator',
# #        'max_f', 'sum_f', 'mean_f', 'var_f', 'peak_f', 'skew_f', 'kurtosis_f',
# #        'gesture', 'participant'])
# # new_df.append(e, ignore_index=True)
# # new_df
# e = e.append(g)
# e

In [144]:
new_df['participant'].unique()

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
       '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39',
       '4', '40', '41', '42', '43', '5', '6', '7', '8', '9'], dtype=object)

In [145]:
new_df.columns

Index(['crest_factor_F1', 'dasd_F1', 'diffvar_F1', 'form_factor_F1', 'iemg_F1',
       'kurtosis_F1', 'kurtosis_f_F1', 'mav_F1', 'max_F1', 'max_f_F1',
       ...
       'rms_W9', 'skew_W9', 'skew_f_W9', 'ssi_W9', 'sum_f_W9', 'var_f_W9',
       'wflen_W9', 'willison_W9', 'gesture', 'participant'],
      dtype='object', length=758)

In [146]:
new_df

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0          7.091099  0.021834    0.000606    -6502.754507  365.456658   
0         13.324514  0.023852    0.000689     1352.897349  379.664639   
0          8.047954  0.016213    0.000326     1295.052394  296.823135   
0          8.459555  0.026572    0.000864    14453.068135  479.688214   
0          8.329011  0.026896    0.000901    11827.310277  464.350257   
..              ...       ...         ...             ...         ...   
0          7.771453  0.013208    0.000208     2599.892725  274.024844   
0          9.172642  0.019135    0.000429     1255.242161  385.695263   
0          5.923115  0.018533    0.000408     1713.228290  389.039490   
0          6.466362  0.015749    0.000292     -992.810528  319.503197   
0          6.331101  0.016365    0.000319     2571.088691  335.584187   

    kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0      2.574033      85.547962  0.035689  0.047925  0.004600  ...  0.022588   
0     16.942218     329.114870  0.037077  0.057235  0.016957  ...  0.016172   
0      3.795827     134.751765  0.028987  0.039620  0.003721  ...  0.017039   
0      6.938354      98.832790  0.046845  0.068228  0.010985  ...  0.031982   
0      2.379207     116.412205  0.045347  0.060540  0.008721  ...  0.031134   
..          ...            ...       ...       ...       ...  ...       ...   
0      2.176596      28.888640  0.026760  0.035561  0.000668  ...  0.020526   
0      4.615531     133.237150  0.037666  0.051690  0.002916  ...  0.025825   
0      1.912226      22.613382  0.037992  0.050501  0.001450  ...  0.027460   
0      2.189195      21.864578  0.031201  0.041789  0.000820  ...  0.013359   
0      1.845409      28.544842  0.032772  0.043372  0.001164  ...  0.015422   

     skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9   wflen_W9  \
0  -0.148877   5.529415   5.224663  0.109574  2.901826e-10  69.944068   
0  -0.205427   9.332349   2.677940  0.077566  2.769772e-10  54.530919   
0  -0.204604   9.078430   2.973002  0.064458  1.426359e-10  57.815909   
0  -0.266818   5.067522  10.473811  0.131909  4.509337e-10  83.441138   
0  -0.092205   5.414199   9.925787  0.177516  9.577100e-10  94.393506   
..       ...        ...        ...       ...           ...        ...   
0  -0.293608   3.830298   4.314177  0.035283  1.966555e-11  40.970398   
0  -0.389927   4.200155   6.829604  0.076162  1.003953e-10  52.342457   
0  -0.321020   4.375813   7.721463  0.081006  1.125954e-10  59.843660   
0  -0.493375   3.832319   1.827333  0.062739  6.332731e-11  35.905471   
0  -0.457244   3.590272   2.435599  0.071311  7.882752e-11  40.497393   

    willison_W9  gesture  participant  
0          15.0       10            1  
0          23.0       10            1  
0          13.0       10            1  
0           0.0       10            1  
0           3.0       10            1  
..          ...      ...          ...  
0           2.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           4.0        9            9  

[15351 rows x 758 columns]

In [76]:
df.reset_index(drop = True, inplace=True)

In [77]:
df.head(10)

session participant gesture trial  \
0       1           1      10     1   
1       1           1      10     2   
2       1           1      10     3   
3       1           1      10     4   
4       1           1      10     5   
5       1           1      10     6   
6       1           1      10     7   
7       1           1      11     1   
8       1           1      11     2   
9       1           1      11     3   

                                            filename  
0  E:\DS5500-project\data\gesture-recognition-and...  
1  E:\DS5500-project\data\gesture-recognition-and...  
2  E:\DS5500-project\data\gesture-recognition-and...  
3  E:\DS5500-project\data\gesture-recognition-and...  
4  E:\DS5500-project\data\gesture-recognition-and...  
5  E:\DS5500-project\data\gesture-recognition-and...  
6  E:\DS5500-project\data\gesture-recognition-and...  
7  E:\DS5500-project\data\gesture-recognition-and...  
8  E:\DS5500-project\data\gesture-recognition-and...  
9  E:\DS5500-project\data\gesture-recognition-and...

In [78]:
output_df = pd.concat([df.drop(columns=['participant', 'gesture']), new_df], axis = 1)

In [79]:
output_df

session trial                                           filename  \
0           1     1  E:\DS5500-project\data\gesture-recognition-and...   
1           1     2  E:\DS5500-project\data\gesture-recognition-and...   
2           1     3  E:\DS5500-project\data\gesture-recognition-and...   
3           1     4  E:\DS5500-project\data\gesture-recognition-and...   
4           1     5  E:\DS5500-project\data\gesture-recognition-and...   
...       ...   ...                                                ...   
15346       3     3  E:\DS5500-project\data\gesture-recognition-and...   
15347       3     4  E:\DS5500-project\data\gesture-recognition-and...   
15348       3     5  E:\DS5500-project\data\gesture-recognition-and...   
15349       3     6  E:\DS5500-project\data\gesture-recognition-and...   
15350       3     7  E:\DS5500-project\data\gesture-recognition-and...   

       crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1    iemg_F1  \
0             3.963505  0.025410    0.000813     -289.344418  21.112081   
1             3.671088  0.021105    0.000555     -106.425561  17.831058   
2             4.612221  0.021962    0.000596       31.279275  21.576849   
3             3.596929  0.059542    0.004202     -101.810923  60.856905   
4             3.369614  0.030592    0.001276      678.680596  27.068893   
...                ...       ...         ...             ...        ...   
15346         3.550602  0.011181    0.000143     -935.693167  12.848445   
15347         3.198854  0.018045    0.000389       89.805074  19.082627   
15348         3.496704  0.022217    0.000586      -65.838778  22.905369   
15349         3.869880  0.016193    0.000319     -327.538075  17.700126   
15350         5.505573  0.020028    0.000453       49.349658  18.496744   

       kurtosis_F1  kurtosis_f_F1  ...    rms_W9   skew_W9  skew_f_W9  \
0         0.919159      31.334996  ...  0.029079  0.072222   2.511020   
1         0.375778      10.495107  ...  0.016885 -0.327373   3.008486   
2         2.312412      21.682307  ...  0.022612 -0.685085   6.404526   
3         1.330189       9.403929  ...  0.037485  0.048006   2.158654   
4         0.023663       3.475985  ...  0.032975  0.239004   3.239978   
...            ...            ...  ...       ...       ...        ...   
15346     0.753193       5.701307  ...  0.020591  0.284598   2.564642   
15347     0.246325       8.584008  ...  0.028650 -0.102584   4.378273   
15348     0.839749       5.800207  ...  0.039886 -0.401008   3.533121   
15349     1.099209      29.351911  ...  0.015737 -0.772348   2.338708   
15350     3.998320      15.428954  ...  0.020040 -0.095961   3.440249   

         ssi_W9  sum_f_W9      var_f_W9  wflen_W9  willison_W9  gesture  \
0      0.432939  0.008130  3.964793e-10  4.738240          0.0       10   
1      0.145968  0.003315  5.777674e-11  2.905545          2.0       10   
2      0.261796  0.007892  7.770187e-10  3.681110          0.0       10   
3      0.719406  0.019679  1.856085e-09  5.631111          0.0       10   
4      0.556730  0.013197  1.026835e-09  5.653857          0.0       10   
...         ...       ...           ...       ...          ...      ...   
15346  0.217072  0.001398  1.094183e-11  2.012504          0.0        9   
15347  0.420250  0.004425  1.455809e-10  2.996039          0.0        9   
15348  0.814526  0.004930  1.681511e-10  3.741230          0.0        9   
15349  0.126796  0.003617  6.669930e-11  1.957923          0.0        9   
15350  0.205623  0.004516  1.158276e-10  2.407260          0.0        9   

       participant  
0                1  
1                1  
2                1  
3                1  
4                1  
...            ...  
15346            9  
15347            9  
15348            9  
15349            9  
15350            9  

[15351 rows x 761 columns]

In [80]:
output_df.to_csv(base_path+"features_v2_250ms.csv", index = False)

In [71]:
output_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15351 entries, 0 to 15350
Columns: 761 entries, session to participant
dtypes: float64(756), object(5)
memory usage: 89.1+ MB
