In [1]:
import numpy as np
import pandas as pd
import os
import sys
import re
import wfdb
import scipy.stats as stats
from scipy.fft import fft, fftfreq

In [2]:
def extract_unique_values_from_folder(folder:str):
    """
    Function to extract just the unique headers of the dat and hea files (removing the file name) 
    """
    unique = set()
    for f in os.listdir(folder):
        unique.add(extract_basename(os.path.join(folder, f)))
        
    return list(unique)

In [3]:
def extract_basename(filename):
    """
    Function to extract just the unique headers of the dat and hea files (removing the file spec) 
    """
    return os.path.splitext(filename)[0]

In [4]:
def extract_info_from_name(filename):
    parsed = {}
    basename = os.path.basename(filename).split(".")[0]
    pattern = r"session(\d+)_participant(\d+)_gesture(\d+)_trial(\d+)"
    match = re.match(pattern, basename)
    parsed['session'] = match.group(1) 
    parsed['participant'] = match.group(2)
    parsed['gesture'] = match.group(3) 
    parsed['trial'] = match.group(4)
    parsed['filename'] = filename
    return parsed

In [5]:
base_path = "../../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/"

In [6]:
session1 = os.path.abspath(base_path+"Session1")
session2 = os.path.abspath(base_path+"Session2")
session3 = os.path.abspath(base_path+"Session3")
unique_values = extract_unique_values_from_folder(session1)

parsed_data_1 = []
parsed_data_2 = []
parsed_data_3 = []

for participant_dir in os.listdir(session1):
    participant_path = os.path.join(session1, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_1.append(extract_info_from_name(file_path))

for participant_dir in os.listdir(session2):
    participant_path = os.path.join(session2, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_2.append(extract_info_from_name(file_path))

for participant_dir in os.listdir(session3):
    participant_path = os.path.join(session3, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_3.append(extract_info_from_name(file_path))

#parsed_data
df1 = pd.DataFrame(parsed_data_1)
df2 = pd.DataFrame(parsed_data_2)
df3 = pd.DataFrame(parsed_data_3)

df = pd.concat([df1, df2, df3], axis=0)
df['filename'] = df['filename'].str.replace('.hea', '')
df

session participant gesture trial  \
0          1           1      10     1   
1          1           1      10     2   
2          1           1      10     3   
3          1           1      10     4   
4          1           1      10     5   
...      ...         ...     ...   ...   
5112       3           9       9     3   
5113       3           9       9     4   
5114       3           9       9     5   
5115       3           9       9     6   
5116       3           9       9     7   

                                               filename  
0     E:\DS5500-project\data\gesture-recognition-and...  
1     E:\DS5500-project\data\gesture-recognition-and...  
2     E:\DS5500-project\data\gesture-recognition-and...  
3     E:\DS5500-project\data\gesture-recognition-and...  
4     E:\DS5500-project\data\gesture-recognition-and...  
...                                                 ...  
5112  E:\DS5500-project\data\gesture-recognition-and...  
5113  E:\DS5500-project\data\gesture-recognition-and...  
5114  E:\DS5500-project\data\gesture-recognition-and...  
5115  E:\DS5500-project\data\gesture-recognition-and...  
5116  E:\DS5500-project\data\gesture-recognition-and...  

[15351 rows x 5 columns]

In [299]:
# df['trial'].unique()

In [300]:
# df['participant'].unique()

In [301]:

# def integrated_EMG(signal):
#     return np.sum(np.abs(signal))

# def mean_absolute_value(signal):
#     return np.mean(np.abs(signal))

# def simple_square_integral(signal):
#     return np.sum(signal**2)

# def root_mean_square(signal):
#     return np.sqrt(np.mean(signal**2))

# def variance(signal):
#     return np.var(signal)

# def myopulse_percentage_rate(signal):
#     return len(np.where(np.diff(np.sign(signal)))[0]) / len(signal)

# def waveform_length(signal):
#     return np.sum(np.abs(np.diff(signal)))

# def difference_variance(signal):
#     return np.var(np.diff(signal))

# def difference_absolute_standard_deviation(signal):
#     return np.std(np.diff(np.abs(signal)))

# def willison_amplitude(signal, threshold=0.1):
#     return np.sum(np.abs(np.diff(signal)) > threshold)

In [46]:
t = np.random.randn(4,4)

th = np.mean(t, axis = 0) + 3 * np.std(t, axis = 0)

In [47]:
np.sum(t>th, axis = 0) / len(t)

array([0., 0., 0., 0.])

In [48]:
t

array([[ 0.85591071,  0.54331365, -1.85640566, -0.87003166],
       [-1.73659211,  1.13693586, -0.5278333 ,  0.23172814],
       [-1.42274195, -0.10289443,  0.083131  ,  1.23514086],
       [-1.76453248,  0.70322284, -1.40655625, -0.3251254 ]])

In [52]:
np.mean(t, axis = 0)

array([-1.01698896,  0.57014448, -0.92691605,  0.06792799])

In [53]:
np.std(t, axis = 0)

array([1.08961446, 0.44515828, 0.75390115, 0.77837582])

In [51]:
th

array([2.25185442, 1.90561932, 1.33478739, 2.40305544])

In [23]:
np.sum(np.abs(np.diff(t, axis = 0)) > th, axis = 0)

array([3, 3, 0, 1])

In [24]:
np.diff(t, axis = 0)

array([[ 0.24130357, -0.68793279,  0.39513564, -0.14393015],
       [-0.02219953,  0.37785449, -0.87299472,  0.50745859],
       [ 0.26304753,  0.14092028, -0.02023823,  0.1617362 ]])

In [ ]:
np.diff()

In [ ]:
np.sum(np.abs(np.diff(time_data, axis = 0)) > th, axis = 0)

In [55]:
def extract_features(df):
    """
    Extracting the following features:
    'MIN','MAX','MEAN','RMS','VAR','STD','POWER','PEAK','P2P','CREST FACTOR','SKEW','KURTOSIS',
            'MAX_f','SUM_f','MEAN_f','VAR_f','PEAK_f','SKEW_f','KURTOSIS_f'
    These will be an array of values for each of the 32 sensors
    """
    #time data
    features = {}
    #time domain features
    time_data = df.values
    #Three std seems excessive. This can be changed later
    th = np.mean(time_data, axis = 0) + 2 * np.std(time_data, axis = 0)
    features['iemg'] = np.sum(np.abs(time_data), axis=0)
    features['mav'] = np.mean(np.abs(time_data), axis=0)
    features['ssi'] = np.sum(time_data**2, axis=0)
    # features['myopulse'] = len(np.where(np.diff(np.sign(time_data)))[0]) / len(time_data)
    #ref = https://github.com/tanmaygadgil/DS5500-project/blob/main/code_snippets/python-sebastian/feature_extraction.py
    features['myopulse'] = np.sum(time_data >= th, axis = 0) / len(time_data)
    features['wflen'] = np.sum(np.abs(np.diff(time_data, axis = 0)), axis=0)
    features['diffvar'] = np.var(np.diff(time_data, axis = 0), axis = 0)
    features['dasd'] = np.std(np.diff(np.abs(time_data), axis = 0), axis = 0)
    #Ref #ref = https://github.com/tanmaygadgil/DS5500-project/blob/main/code_snippets/python-sebastian/feature_extraction.py
    features['willison'] = np.sum(np.abs(np.diff(time_data, axis = 0)) > th, axis = 0)
    
    features['mean'] = np.mean(time_data, axis = 0)
    features['min'] = np.min(time_data, axis = 0)
    features['max'] = np.max(time_data, axis = 0)
    features['rms'] = np.sqrt(np.mean(time_data**2, axis = 0))
    features['max'] = np.std(time_data, axis = 0)
    features['power'] = np.mean(time_data**2, axis = 0)
    features['peak'] = np.max(np.abs(time_data), axis = 0)
    features['p2p'] = np.ptp(time_data, axis = 0)
    features['crest_factor'] = np.max(np.abs(time_data), axis = 0)/np.sqrt(np.mean(time_data**2, axis = 0))
    features['skew'] = stats.skew(time_data, axis = 0)
    features['kurtosis'] = stats.kurtosis(time_data, axis = 0)
    features['form_factor'] =np.sqrt(np.mean(time_data**2, axis = 0)) / np.mean(time_data, axis = 0)
    features['pulse_indicator'] = np.max(np.abs(time_data), axis = 0)/np.mean(time_data, axis = 0) 
    
    #Convert to frequency domain
    freq_data = fft(time_data)
    S_f = np.abs(freq_data**2)/len(df)
    features['max_f'] = np.max(S_f, axis = 0)
    features['sum_f'] = np.sum(S_f, axis = 0)
    features['mean_f'] = np.mean(S_f, axis = 0)
    features['var_f'] = np.var(S_f, axis = 0)
    features['peak_f'] = np.max(np.abs(S_f), axis = 0)
    features['skew_f'] = stats.skew(S_f, axis = 0)
    features['kurtosis_f'] = stats.kurtosis(S_f, axis = 0)
    
    return features
    

In [56]:
from tqdm import tqdm

In [ ]:
new_df = pd.DataFrame()
for i in tqdm(range(len(df))):
    wave = wfdb.rdrecord(df['filename'].iloc[i])
    wave_df = wave.to_dataframe()
    wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
    f = extract_features(wave_df)
    f['gesture'] = df['gesture'].iloc[i]
    f['participant'] = df['participant'].iloc[i]

    e = pd.DataFrame.from_dict(f, orient='index').T
    new_df = pd.concat([new_df, e])

new_df

 74%|████████████████████████████████████████████████████████▍                   | 11400/15351 [56:10<30:48,  2.14it/s]

In [368]:
new_df.reset_index()

index          iemg       mav          ssi  myopulse        wflen  \
0          0  12527.173912  0.043691  1114.276499  4.272852  6654.991878   
1          0   4995.909239  0.017424   155.117851  5.352344  3172.573858   
2          0   2761.574404  0.009632    49.810684  3.706152  1145.086276   
3          0  15737.169767  0.054887  1582.133054  3.608496  7019.840947   
4          0   5779.696596  0.020158   234.385913  2.704883  2196.760459   
...      ...           ...       ...          ...       ...          ...   
15346      0  12265.030151  0.042777  1397.402511  5.405273  8530.122413   
15347      0   8162.702779  0.028469   537.170042  5.141504  4462.195065   
15348      0  16413.495111  0.057246  2270.720352   5.24209  9207.583257   
15349      0  18656.975851   0.06507  3294.742742  4.512012   9743.69967   
15350      0   9684.781156  0.033778   677.994455  5.513477  6647.202727   

        diffvar      dasd willison  \
0      0.001284  0.032037     6221   
1      0.000262  0.013734       66   
2      0.000043   0.00566        2   
3      0.001321  0.032525     5706   
4      0.000184  0.012485      363   
...         ...       ...      ...   
15346  0.002867  0.045659    15295   
15347  0.000733  0.022413     3204   
15348   0.00289   0.04761    16795   
15349   0.00481  0.061085    25812   
15350  0.001549  0.032239     7487   

                                                    mean  ...  \
0      [-3.3865626032371843e-06, -1.8127820411250496e...  ...   
1      [-2.4296390143113294e-05, -2.8655309194855e-05...  ...   
2      [-1.3949779847863498e-05, -2.4062174569915226e...  ...   
3      [1.1641840060145082e-05, -4.215142767499504e-0...  ...   
4      [-3.33143730828046e-05, -1.780150324510748e-05...  ...   
...                                                  ...  ...   
15346  [1.6498772082619616e-05, 3.2853538128259262e-0...  ...   
15347  [-1.2198009758019286e-06, 6.583611698426713e-0...  ...   
15348  [-6.700379186944414e-05, -0.000101744622133766...  ...   
15349  [-0.00012418053231595642, -0.00011279260799871...  ...   
15350  [1.0188134715096323e-05, 9.757962290590685e-06...  ...   

                                         pulse_indicator  \
0      [-37407.76019983317, -9928.510290468545, -1250...   
1      [-3348.583377997243, -3083.5750782146765, -517...   
2      [-3634.505130751411, -2337.1056508721085, -392...   
3      [31793.081972218017, -92983.68498630782, 20225...   
4      [-4256.367247530787, -7814.248304572609, -7381...   
...                                                  ...   
15346  [10807.896858294565, 60095.275471700355, 16404...   
15347  [-245081.20113310288, 57295.65733937707, -1134...   
15348  [-6489.406370384305, -8204.869278047843, -2114...   
15349  [-4128.165932320242, -4551.086574438503, -4868...   
15350  [20720.36142211757, 24692.630684232987, 20488....   

                                                   max_f  \
0      [0.0032374708895371988, 0.0024257368417489157,...   
1      [0.0003400682853082485, 8.998830278752999e-05,...   
2      [0.00011443323193111958, 0.0001161171355056197...   
3      [0.008602481339282963, 0.0017454534757986016, ...   
4      [0.0011822720162164696, 0.00028295531801698513...   
...                                                  ...   
15346  [0.005726731252394037, 0.0032628507498287016, ...   
15347  [0.003300095685778511, 0.001529226366693726, 4...   
15348  [0.006344236526696033, 0.002330297622180038, 0...   
15349  [0.012855727171059806, 0.004497041382583255, 0...   
15350  [0.0019456444701340674, 0.0010183429795102823,...   

                                                   sum_f  \
0      [1.1552661529428505, 0.52725591139991, 0.05370...   
1      [0.15571759620376374, 0.05185293690611252, 0.0...   
2      [0.058170294893887545, 0.023942600676462675, 0...   
3      [2.0481391254998913, 0.6776872349640545, 0.051...   
4      [0.3000423879830985, 0.10784719651565663, 0.00...   
...                                                  .

In [370]:
# new_df1 = pd.DataFrame()
# for i in range(10):
#     wave = wfdb.rdrecord(df['filename'].iloc[i])
#     wave_df = wave.to_dataframe()
#     wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
#     f = extract_features(wave_df)
#     f['gesture'] = df['gesture'].iloc[i]
#     f['participant'] = df['participant'].iloc[i]

#     e = pd.DataFrame.from_dict(f, orient='index').T
#     new_df1 = new_df1.append(e, ignore_index = False)

# new_df1.reset_index()

In [369]:
new_df.reset_index().to_csv('/Users/rahul/Downloads/features.csv')

In [371]:
# i = 53
# wave = wfdb.rdrecord(df['filename'].iloc[i])
# wave_df = wave.to_dataframe()
# wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
# f = extract_features(wave_df)
# f['gesture'] = df['gesture'].iloc[i]
# f['participant'] = df['participant'].iloc[i]

# g = pd.DataFrame.from_dict(f, orient='index').T

# # new_df = pd.DataFrame(columns = ['iemg', 'mav', 'ssi', 'myopulse', 'wflen', 'diffvar', 'dasd',
# #        'willison', 'mean', 'min', 'max', 'rms', 'power', 'peak', 'p2p',
# #        'crest_factor', 'skew', 'kurtosis', 'form_factor', 'pulse_indicator',
# #        'max_f', 'sum_f', 'mean_f', 'var_f', 'peak_f', 'skew_f', 'kurtosis_f',
# #        'gesture', 'participant'])
# # new_df.append(e, ignore_index=True)
# # new_df
# e = e.append(g)
# e