In [1]:
import numpy as np
import pandas as pd
import os
import sys
import re
import wfdb
import scipy.stats as stats
from scipy.fft import fft, fftfreq

In [2]:
def extract_unique_values_from_folder(folder:str):
    """
    Function to extract just the unique headers of the dat and hea files (removing the file name) 
    """
    unique = set()
    for f in os.listdir(folder):
        unique.add(extract_basename(os.path.join(folder, f)))
        
    return list(unique)

In [3]:
def extract_basename(filename):
    """
    Function to extract just the unique headers of the dat and hea files (removing the file spec) 
    """
    return os.path.splitext(filename)[0]

In [4]:
def extract_info_from_name(filename):
    parsed = {}
    basename = os.path.basename(filename).split(".")[0]
    pattern = r"session(\d+)_participant(\d+)_gesture(\d+)_trial(\d+)"
    match = re.match(pattern, basename)
    parsed['session'] = match.group(1) 
    parsed['participant'] = match.group(2)
    parsed['gesture'] = match.group(3) 
    parsed['trial'] = match.group(4)
    parsed['filename'] = filename
    return parsed

In [5]:
base_path = "../../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/"

In [118]:
session1 = os.path.abspath(base_path+"Session1")
session2 = os.path.abspath(base_path+"Session2")
session3 = os.path.abspath(base_path+"Session3")
unique_values = extract_unique_values_from_folder(session1)

parsed_data_1 = []
parsed_data_2 = []
parsed_data_3 = []

for participant_dir in os.listdir(session1):
    participant_path = os.path.join(session1, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_1.append(extract_info_from_name(file_path))

for participant_dir in os.listdir(session2):
    participant_path = os.path.join(session2, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_2.append(extract_info_from_name(file_path))

for participant_dir in os.listdir(session3):
    participant_path = os.path.join(session3, participant_dir)
    if os.path.isdir(participant_path):
        # Loop through files in participant directory
        for file_name in os.listdir(participant_path):
            if file_name.endswith(".hea"):  # Process only .hea files
                file_path = os.path.join(participant_path, file_name)
                if os.path.isfile(file_path):
                    parsed_data_3.append(extract_info_from_name(file_path))

#parsed_data
df1 = pd.DataFrame(parsed_data_1)
df2 = pd.DataFrame(parsed_data_2)
df3 = pd.DataFrame(parsed_data_3)

df = pd.concat([df1, df2, df3], axis=0)
# df = df1.iloc[:10, :]
df['filename'] = df['filename'].str.replace('.hea', '')
df

session participant gesture trial  \
0          1           1      10     1   
1          1           1      10     2   
2          1           1      10     3   
3          1           1      10     4   
4          1           1      10     5   
...      ...         ...     ...   ...   
5112       3           9       9     3   
5113       3           9       9     4   
5114       3           9       9     5   
5115       3           9       9     6   
5116       3           9       9     7   

                                               filename  
0     E:\DS5500-project\data\gesture-recognition-and...  
1     E:\DS5500-project\data\gesture-recognition-and...  
2     E:\DS5500-project\data\gesture-recognition-and...  
3     E:\DS5500-project\data\gesture-recognition-and...  
4     E:\DS5500-project\data\gesture-recognition-and...  
...                                                 ...  
5112  E:\DS5500-project\data\gesture-recognition-and...  
5113  E:\DS5500-project\data\gesture-recognition-and...  
5114  E:\DS5500-project\data\gesture-recognition-and...  
5115  E:\DS5500-project\data\gesture-recognition-and...  
5116  E:\DS5500-project\data\gesture-recognition-and...  

[15351 rows x 5 columns]

In [119]:
# df['trial'].unique()

In [120]:
# df['participant'].unique()

In [121]:

# def integrated_EMG(signal):
#     return np.sum(np.abs(signal))

# def mean_absolute_value(signal):
#     return np.mean(np.abs(signal))

# def simple_square_integral(signal):
#     return np.sum(signal**2)

# def root_mean_square(signal):
#     return np.sqrt(np.mean(signal**2))

# def variance(signal):
#     return np.var(signal)

# def myopulse_percentage_rate(signal):
#     return len(np.where(np.diff(np.sign(signal)))[0]) / len(signal)

# def waveform_length(signal):
#     return np.sum(np.abs(np.diff(signal)))

# def difference_variance(signal):
#     return np.var(np.diff(signal))

# def difference_absolute_standard_deviation(signal):
#     return np.std(np.diff(np.abs(signal)))

# def willison_amplitude(signal, threshold=0.1):
#     return np.sum(np.abs(np.diff(signal)) > threshold)

In [122]:
t = np.random.randn(10,4)

th = np.mean(t, axis = 0) + 3 * np.std(t, axis = 0)

In [123]:
th

array([3.53320721, 3.82634451, 3.23082561, 1.6049687 ])

In [124]:
np.mean(t, axis = 0)

array([ 0.1260221 ,  0.11618935,  0.78446029, -0.4030366 ])

In [125]:
 np.sum(t**2, axis=0)

array([13.05760502, 15.42972331, 12.80344981,  6.10447978])

In [126]:
np.mean(t, axis = 0)

array([ 0.1260221 ,  0.11618935,  0.78446029, -0.4030366 ])

In [127]:
np.std(t, axis = 0)

array([1.13572837, 1.23671839, 0.8154551 , 0.6693351 ])

In [128]:
th

array([3.53320721, 3.82634451, 3.23082561, 1.6049687 ])

In [129]:
np.sum(np.abs(np.diff(t, axis = 0)) > th, axis = 0)

array([0, 0, 0, 0])

In [130]:
np.diff(t, axis = 0)

array([[ 2.99335433, -3.45811759,  0.26152882,  0.24160798],
       [-2.34207696,  2.35791158,  1.56628613, -0.24404068],
       [ 0.36437501, -3.22662996, -0.1890656 , -1.14076241],
       [ 0.14327592,  3.17231789,  0.93899233,  0.71616219],
       [-0.37651959,  0.05651657, -0.56747082,  0.25337814],
       [-2.31498092, -1.71324716, -0.18585936, -1.42222018],
       [ 2.53359462,  0.0922157 ,  0.44544493,  1.21581115],
       [-1.37045244,  0.90993165, -0.59303695,  1.33051117],
       [ 0.15225351, -0.74953327, -0.94581912, -1.37692946]])

In [134]:
cols = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11',
       'F12', 'F13', 'F14', 'F15', 'F16', 'W1', 'W2', 'W3', 'W4', 'W5', 'W6',
       'W7', 'W8', 'W9', 'W10', 'W11', 'W12']

In [135]:
def extract_features(df):
    """
    Extracting the following features:
    'MIN','MAX','MEAN','RMS','VAR','STD','POWER','PEAK','P2P','CREST FACTOR','SKEW','KURTOSIS',
            'MAX_f','SUM_f','MEAN_f','VAR_f','PEAK_f','SKEW_f','KURTOSIS_f'
    These will be an array of values for each of the 32 sensors
    """
    #time data
    features = {}
    #time domain features
    time_data = df.values
    #Three std seems excessive. This can be changed later
    th = np.mean(time_data, axis = 0) + 2 * np.std(time_data, axis = 0)
    features['iemg'] = np.sum(np.abs(time_data), axis=0)
    features['mav'] = np.mean(np.abs(time_data), axis=0)
    features['ssi'] = np.sum(time_data**2, axis=0)
    # features['myopulse'] = len(np.where(np.diff(np.sign(time_data)))[0]) / len(time_data)
    #ref = https://github.com/tanmaygadgil/DS5500-project/blob/main/code_snippets/python-sebastian/feature_extraction.py
    features['myopulse'] = np.sum(time_data >= th, axis = 0) / len(time_data)
    features['wflen'] = np.sum(np.abs(np.diff(time_data, axis = 0)), axis=0)
    features['diffvar'] = np.var(np.diff(time_data, axis = 0), axis = 0)
    features['dasd'] = np.std(np.diff(np.abs(time_data), axis = 0), axis = 0)
    #Ref #ref = https://github.com/tanmaygadgil/DS5500-project/blob/main/code_snippets/python-sebastian/feature_extraction.py
    features['willison'] = np.sum(np.abs(np.diff(time_data, axis = 0)) > th, axis = 0)
    
    features['mean'] = np.mean(time_data, axis = 0)
    features['min'] = np.min(time_data, axis = 0)
    features['max'] = np.max(time_data, axis = 0)
    features['rms'] = np.sqrt(np.mean(time_data**2, axis = 0))
    features['max'] = np.std(time_data, axis = 0)
    features['power'] = np.mean(time_data**2, axis = 0)
    features['peak'] = np.max(np.abs(time_data), axis = 0)
    features['p2p'] = np.ptp(time_data, axis = 0)
    features['crest_factor'] = np.max(np.abs(time_data), axis = 0)/np.sqrt(np.mean(time_data**2, axis = 0))
    features['skew'] = stats.skew(time_data, axis = 0)
    features['kurtosis'] = stats.kurtosis(time_data, axis = 0)
    features['form_factor'] =np.sqrt(np.mean(time_data**2, axis = 0)) / np.mean(time_data, axis = 0)
    features['pulse_indicator'] = np.max(np.abs(time_data), axis = 0)/np.mean(time_data, axis = 0) 
    
    #Convert to frequency domain
    freq_data = fft(time_data)
    S_f = np.abs(freq_data**2)/len(df)
    features['max_f'] = np.max(S_f, axis = 0)
    features['sum_f'] = np.sum(S_f, axis = 0)
    features['mean_f'] = np.mean(S_f, axis = 0)
    features['var_f'] = np.var(S_f, axis = 0)
    features['peak_f'] = np.max(np.abs(S_f), axis = 0)
    features['skew_f'] = stats.skew(S_f, axis = 0)
    features['kurtosis_f'] = stats.kurtosis(S_f, axis = 0)
    
    return features
    

In [136]:
from tqdm import tqdm

In [84]:
wave = wfdb.rdrecord(df['filename'].iloc[0])
wave_df = wave.to_dataframe()
wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)

In [85]:
wave_df

F1        F2        F3        F4        F5  \
0 days 00:00:00            0.018842  0.003025  0.046460  0.104214  0.078568   
0 days 00:00:00.000488281  0.007086 -0.007874  0.004497  0.054350 -0.043084   
0 days 00:00:00.000976562 -0.018860 -0.037642 -0.040174 -0.003930 -0.175231   
0 days 00:00:00.001464843 -0.013056 -0.036159 -0.049285 -0.019746 -0.233636   
0 days 00:00:00.001953124  0.025837  0.006250 -0.017654  0.013535 -0.205318   
...                             ...       ...       ...       ...       ...   
0 days 00:00:04.997556035 -0.046034 -0.075884 -0.073877 -0.076665 -0.115671   
0 days 00:00:04.998044316 -0.016398 -0.042997 -0.033536 -0.052874 -0.050325   
0 days 00:00:04.998532597  0.001108 -0.024600 -0.008593 -0.027242 -0.008290   
0 days 00:00:04.999020878  0.003021 -0.018727 -0.003628 -0.012806 -0.012712   
0 days 00:00:04.999509159 -0.002728 -0.012182 -0.004230 -0.013803 -0.033760   

                                 F6        F7        F8        F9       F10  \
0 days 00:00:00            0.139992  0.093088  0.033105  0.003268 -0.046261   
0 days 00:00:00.000488281  0.000402  0.053829  0.018269  0.013704 -0.032529   
0 days 00:00:00.000976562 -0.169030 -0.003461 -0.003630 -0.009620 -0.050602   
0 days 00:00:00.001464843 -0.278486 -0.028711 -0.003322 -0.020864 -0.047258   
0 days 00:00:00.001953124 -0.291812 -0.012940  0.019870  0.004719 -0.003508   
...                             ...       ...       ...       ...       ...   
0 days 00:00:04.997556035 -0.118026 -0.048888 -0.043507 -0.046553 -0.068948   
0 days 00:00:04.998044316 -0.047177 -0.006694 -0.010307 -0.014983 -0.036733   
0 days 00:00:04.998532597 -0.007932  0.023454  0.010110 -0.000144 -0.024079   
0 days 00:00:04.999020878 -0.004160  0.032820  0.016069 -0.001028 -0.023260   
0 days 00:00:04.999509159 -0.012037  0.025776  0.013484 -0.005709 -0.017404   

                           ...        W3        W4        W5        W6  \
0 days 00:00:00            ...  0.013156 -0.041120 -0.085215  0.001288   
0 days 00:00:00.000488281  ... -0.021570 -0.043785 -0.120230 -0.029939   
0 days 00:00:00.000976562  ... -0.032417 -0.050653 -0.124954 -0.034229   
0 days 00:00:00.001464843  ... -0.024087 -0.049352 -0.109183 -0.034107   
0 days 00:00:00.001953124  ... -0.002855 -0.024827 -0.082030 -0.039545   
...                        ...       ...       ...       ...       ...   
0 days 00:00:04.997556035  ... -0.006198 -0.006975  0.028131  0.032132   
0 days 00:00:04.998044316  ... -0.006423 -0.009028  0.035122  0.045688   
0 days 00:00:04.998532597  ... -0.005212 -0.002708  0.042888  0.058652   
0 days 00:00:04.999020878  ...  0.001042  0.006685  0.045966  0.057129   
0 days 00:00:04.999509159  ...  0.010903  0.012682  0.041373  0.042895   

                                 W7        W8        W9       W10       W11  \
0 days 00:00:00            0.099477  0.077323  0.006146 -0.032260 -0.080570   
0 days 00:00:00.000488281  0.118181  0.076367 -0.011716 -0.036650 -0.117002   
0 days 00:00:00.000976562  0.126799  0.077234 -0.018928 -0.040363 -0.123522   
0 days 00:00:00.001464843  0.109105  0.067106 -0.017590 -0.037744 -0.108100   
0 days 00:00:00.001953124  0.057957  0.042862 -0.012414 -0.026509 -0.081828   
...                             ...       ...       ...       ...       ...   
0 days 00:00:04.997556035 -0.009935  0.007103 -0.004418 -0.006439  0.023369   
0 days 00:00:04.998044316  0.011053  0.014663 -0.002744 -0.001974  0.031485   
0 days 00:00:04.998532597  0.023663  0.012143 -0.002599  0.002870  0.042420   
0 days 00:00:04.999020878  0.017105  0.003124 -0.002948  0.004054  0.047149   
0 days 00:00:04.999509159  0.004568  0.000278 -0.002191  0.002454  0.041754   

                                W12  
0 days 00:00:00            0.010847  
0 days 00:00:00.000488281 -0.010532  
0 days 00:00:00.000976562 -0.021235  
0 days 00:00:00.001464843 -0.025145  
0 days 00:00:00.001953124 -0.032091  
...                             ...  
0 days 00:00:04.997556035  0.01

In [86]:
cols = wave_df.columns

In [87]:
cols

Index(['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11',
       'F12', 'F13', 'F14', 'F15', 'F16', 'W1', 'W2', 'W3', 'W4', 'W5', 'W6',
       'W7', 'W8', 'W9', 'W10', 'W11', 'W12'],
      dtype='object')

In [88]:
f = extract_features(wave_df)

In [91]:
f

{'iemg': array([365.45665831, 486.2520967 , 572.29991509, 549.59147577,
        596.68857045, 574.35190439, 410.86856226, 340.19879641,
        406.83270407, 550.19696813, 546.10203721, 610.10055259,
        614.92412744, 617.93006649, 441.81474245, 389.79408233,
        395.75247076, 316.91692102, 318.13335483, 420.81227781,
        427.66678497, 374.33304146, 270.31216611, 241.42230482,
        174.74936456, 219.91073327, 431.81029796, 331.64010952]),
 'mav': array([0.03568913, 0.04748556, 0.05588866, 0.05367104, 0.05827037,
        0.05608905, 0.04012388, 0.03322254, 0.03972976, 0.05373017,
        0.05333028, 0.05958013, 0.06005118, 0.06034473, 0.04314597,
        0.03806583, 0.0386477 , 0.03094892, 0.03106771, 0.04109495,
        0.04176433, 0.03655596, 0.02639767, 0.0235764 , 0.01706537,
        0.02147566, 0.04216897, 0.03238673]),
 'ssi': array([23.51964209, 42.42566996, 61.31071888, 56.9693793 , 62.63437547,
        58.45371472, 28.43166296, 19.79431186, 29.34707639, 54.767860

In [103]:
a = pd.DataFrame(f, index=cols)

In [104]:
a = a.unstack().to_frame().sort_index(level=1).T

In [105]:
a.columns

MultiIndex([(   'crest_factor', 'F1'),
            (           'dasd', 'F1'),
            (        'diffvar', 'F1'),
            (    'form_factor', 'F1'),
            (           'iemg', 'F1'),
            (       'kurtosis', 'F1'),
            (     'kurtosis_f', 'F1'),
            (            'mav', 'F1'),
            (            'max', 'F1'),
            (          'max_f', 'F1'),
            ...
            (          'power', 'W9'),
            ('pulse_indicator', 'W9'),
            (            'rms', 'W9'),
            (           'skew', 'W9'),
            (         'skew_f', 'W9'),
            (            'ssi', 'W9'),
            (          'sum_f', 'W9'),
            (          'var_f', 'W9'),
            (          'wflen', 'W9'),
            (       'willison', 'W9')],
           length=756)

In [101]:
a.columns = a.columns.map('_'.join)

In [102]:
a

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0         7.091099  0.021834    0.000606    -6502.754507  365.456658   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...  power_W9  \
0     2.574033      85.547962  0.035689  0.047925    0.0046  ...   0.00051   

   pulse_indicator_W9    rms_W9   skew_W9  skew_f_W9    ssi_W9  sum_f_W9  \
0       -22508.900332  0.022588 -0.148877   5.529415  5.224663  0.109574   

       var_f_W9   wflen_W9  willison_W9  
0  2.901826e-10  69.944068         15.0  

[1 rows x 756 columns]

In [107]:
temp

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0         7.091099  0.021834    0.000606    -6502.754507  365.456658   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0     2.574033      85.547962  0.035689  0.047925    0.0046  ...  0.022588   

    skew_W9  skew_f_W9    ssi_W9  sum_f_W9      var_f_W9   wflen_W9  \
0 -0.148877   5.529415  5.224663  0.109574  2.901826e-10  69.944068   

   willison_W9  gesture  participant  
0         15.0       10            1  

[1 rows x 758 columns]

In [137]:
df_list = []
for i in tqdm(range(len(df))):
    wave = wfdb.rdrecord(df['filename'].iloc[i])
    wave_df = wave.to_dataframe()
    wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
    f = extract_features(wave_df)
    temp = pd.DataFrame(f, index=cols)
    temp = temp.unstack().to_frame().sort_index(level=1).T
    temp.columns = temp.columns.map('_'.join)
    temp['gesture'] = df['gesture'].iloc[i]
    temp['participant'] = df['participant'].iloc[i]

    # e = pd.DataFrame.from_dict(temp, orient='index').T
    # new_df = pd.concat([new_df, temp])
    df_list.append(temp)

new_df = pd.concat(df_list)

new_df

100%|████████████████████████████████████████████████████████████████████████████| 15351/15351 [39:10<00:00,  6.53it/s]


crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0          7.091099  0.021834    0.000606    -6502.754507  365.456658   
0         13.324514  0.023852    0.000689     1352.897349  379.664639   
0          8.047954  0.016213    0.000326     1295.052394  296.823135   
0          8.459555  0.026572    0.000864    14453.068135  479.688214   
0          8.329011  0.026896    0.000901    11827.310277  464.350257   
..              ...       ...         ...             ...         ...   
0          7.771453  0.013208    0.000208     2599.892725  274.024844   
0          9.172642  0.019135    0.000429     1255.242161  385.695263   
0          5.923115  0.018533    0.000408     1713.228290  389.039490   
0          6.466362  0.015749    0.000292     -992.810528  319.503197   
0          6.331101  0.016365    0.000319     2571.088691  335.584187   

    kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0      2.574033      85.547962  0.035689  0.047925  0.004600  ...  0.022588   
0     16.942218     329.114870  0.037077  0.057235  0.016957  ...  0.016172   
0      3.795827     134.751765  0.028987  0.039620  0.003721  ...  0.017039   
0      6.938354      98.832790  0.046845  0.068228  0.010985  ...  0.031982   
0      2.379207     116.412205  0.045347  0.060540  0.008721  ...  0.031134   
..          ...            ...       ...       ...       ...  ...       ...   
0      2.176596      28.888640  0.026760  0.035561  0.000668  ...  0.020526   
0      4.615531     133.237150  0.037666  0.051690  0.002916  ...  0.025825   
0      1.912226      22.613382  0.037992  0.050501  0.001450  ...  0.027460   
0      2.189195      21.864578  0.031201  0.041789  0.000820  ...  0.013359   
0      1.845409      28.544842  0.032772  0.043372  0.001164  ...  0.015422   

     skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9   wflen_W9  \
0  -0.148877   5.529415   5.224663  0.109574  2.901826e-10  69.944068   
0  -0.205427   9.332349   2.677940  0.077566  2.769772e-10  54.530919   
0  -0.204604   9.078430   2.973002  0.064458  1.426359e-10  57.815909   
0  -0.266818   5.067522  10.473811  0.131909  4.509337e-10  83.441138   
0  -0.092205   5.414199   9.925787  0.177516  9.577100e-10  94.393506   
..       ...        ...        ...       ...           ...        ...   
0  -0.293608   3.830298   4.314177  0.035283  1.966555e-11  40.970398   
0  -0.389927   4.200155   6.829604  0.076162  1.003953e-10  52.342457   
0  -0.321020   4.375813   7.721463  0.081006  1.125954e-10  59.843660   
0  -0.493375   3.832319   1.827333  0.062739  6.332731e-11  35.905471   
0  -0.457244   3.590272   2.435599  0.071311  7.882752e-11  40.497393   

    willison_W9  gesture  participant  
0          15.0       10            1  
0          23.0       10            1  
0          13.0       10            1  
0           0.0       10            1  
0           3.0       10            1  
..          ...      ...          ...  
0           2.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           4.0        9            9  

[15351 rows x 758 columns]

In [138]:
new_df.reset_index()

index  crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1  \
0          0         7.091099  0.021834    0.000606    -6502.754507   
1          0        13.324514  0.023852    0.000689     1352.897349   
2          0         8.047954  0.016213    0.000326     1295.052394   
3          0         8.459555  0.026572    0.000864    14453.068135   
4          0         8.329011  0.026896    0.000901    11827.310277   
...      ...              ...       ...         ...             ...   
15346      0         7.771453  0.013208    0.000208     2599.892725   
15347      0         9.172642  0.019135    0.000429     1255.242161   
15348      0         5.923115  0.018533    0.000408     1713.228290   
15349      0         6.466362  0.015749    0.000292     -992.810528   
15350      0         6.331101  0.016365    0.000319     2571.088691   

          iemg_F1  kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  ...  \
0      365.456658     2.574033      85.547962  0.035689  0.047925  ...   
1      379.664639    16.942218     329.114870  0.037077  0.057235  ...   
2      296.823135     3.795827     134.751765  0.028987  0.039620  ...   
3      479.688214     6.938354      98.832790  0.046845  0.068228  ...   
4      464.350257     2.379207     116.412205  0.045347  0.060540  ...   
...           ...          ...            ...       ...       ...  ...   
15346  274.024844     2.176596      28.888640  0.026760  0.035561  ...   
15347  385.695263     4.615531     133.237150  0.037666  0.051690  ...   
15348  389.039490     1.912226      22.613382  0.037992  0.050501  ...   
15349  319.503197     2.189195      21.864578  0.031201  0.041789  ...   
15350  335.584187     1.845409      28.544842  0.032772  0.043372  ...   

         rms_W9   skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9  \
0      0.022588 -0.148877   5.529415   5.224663  0.109574  2.901826e-10   
1      0.016172 -0.205427   9.332349   2.677940  0.077566  2.769772e-10   
2      0.017039 -0.204604   9.078430   2.973002  0.064458  1.426359e-10   
3      0.031982 -0.266818   5.067522  10.473811  0.131909  4.509337e-10   
4      0.031134 -0.092205   5.414199   9.925787  0.177516  9.577100e-10   
...         ...       ...        ...        ...       ...           ...   
15346  0.020526 -0.293608   3.830298   4.314177  0.035283  1.966555e-11   
15347  0.025825 -0.389927   4.200155   6.829604  0.076162  1.003953e-10   
15348  0.027460 -0.321020   4.375813   7.721463  0.081006  1.125954e-10   
15349  0.013359 -0.493375   3.832319   1.827333  0.062739  6.332731e-11   
15350  0.015422 -0.457244   3.590272   2.435599  0.071311  7.882752e-11   

        wflen_W9  willison_W9  gesture  participant  
0      69.944068         15.0       10            1  
1      54.530919         23.0       10            1  
2      57.815909         13.0       10            1  
3      83.441138          0.0       10            1  
4      94.393506          3.0       10            1  
...          ...          ...      ...          ...  
15346  40.970398          2.0        9            9  
15347  52.342457          0.0        9            9  
15348  59.843660          0.0        9            9  
15349  35.905471          0.0        9            9  
15350  40.497393          4.0        9            9  

[15351 rows x 759 columns]

In [150]:
new_df.reset_index(inplace=True, drop=True)

In [152]:
new_df.head(10)

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1      iemg_F1  \
0         7.091099  0.021834    0.000606    -6502.754507   365.456658   
1        13.324514  0.023852    0.000689     1352.897349   379.664639   
2         8.047954  0.016213    0.000326     1295.052394   296.823135   
3         8.459555  0.026572    0.000864    14453.068135   479.688214   
4         8.329011  0.026896    0.000901    11827.310277   464.350257   
5         8.674404  0.017401    0.000378    12136.826257   280.796436   
6         8.099232  0.032150    0.001249    19275.119794   583.156005   
7         7.905986  0.058204    0.004107    -1123.478043  1094.278406   
8         7.473734  0.059286    0.004278     1563.499877  1086.929564   
9         4.950507  0.050075    0.003132   -53607.972529   941.080017   

   kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0     2.574033      85.547962  0.035689  0.047925  0.004600  ...  0.022588   
1    16.942218     329.114870  0.037077  0.057235  0.016957  ...  0.016172   
2     3.795827     134.751765  0.028987  0.039620  0.003721  ...  0.017039   
3     6.938354      98.832790  0.046845  0.068228  0.010985  ...  0.031982   
4     2.379207     116.412205  0.045347  0.060540  0.008721  ...  0.031134   
5     7.259443     263.526169  0.027422  0.041415  0.008846  ...  0.023466   
6     4.634717      88.257105  0.056949  0.081582  0.017235  ...  0.042043   
7     4.396108      74.700021  0.106863  0.151744  0.042724  ...  0.032784   
8     3.646588      93.967309  0.106145  0.147920  0.040994  ...  0.030829   
9     1.469007      29.758598  0.091902  0.122266  0.014425  ...  0.031556   

    skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9    wflen_W9  \
0 -0.148877   5.529415   5.224663  0.109574  2.901826e-10   69.944068   
1 -0.205427   9.332349   2.677940  0.077566  2.769772e-10   54.530919   
2 -0.204604   9.078430   2.973002  0.064458  1.426359e-10   57.815909   
3 -0.266818   5.067522  10.473811  0.131909  4.509337e-10   83.441138   
4 -0.092205   5.414199   9.925787  0.177516  9.577100e-10   94.393506   
5 -0.188011   9.449841   5.638683  0.091060  4.224819e-10   64.923909   
6 -0.340548   6.431865  18.100727  0.253271  2.580174e-09  103.737954   
7  0.125052   9.367073  11.006132  0.442489  8.439766e-09  109.261253   
8  0.013163   8.248502   9.732376  0.416936  7.500715e-09  111.205787   
9 -0.000280   4.730823  10.196812  0.286288  2.015109e-09  114.999665   

   willison_W9  gesture  participant  
0         15.0       10            1  
1         23.0       10            1  
2         13.0       10            1  
3          0.0       10            1  
4          3.0       10            1  
5         11.0       10            1  
6          4.0       10            1  
7          8.0       11            1  
8         27.0       11            1  
9         12.0       11            1  

[10 rows x 758 columns]

In [370]:
# new_df1 = pd.DataFrame()
# for i in range(10):
#     wave = wfdb.rdrecord(df['filename'].iloc[i])
#     wave_df = wave.to_dataframe()
#     wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
#     f = extract_features(wave_df)
#     f['gesture'] = df['gesture'].iloc[i]
#     f['participant'] = df['participant'].iloc[i]

#     e = pd.DataFrame.from_dict(f, orient='index').T
#     new_df1 = new_df1.append(e, ignore_index = False)

# new_df1.reset_index()

In [139]:
new_df.reset_index(drop=True).to_csv(base_path+"features_v2.csv", index = False)

In [371]:
# i = 53
# wave = wfdb.rdrecord(df['filename'].iloc[i])
# wave_df = wave.to_dataframe()
# wave_df = wave_df.drop(['U1','U2', 'U3','U4'], axis = 1)
# f = extract_features(wave_df)
# f['gesture'] = df['gesture'].iloc[i]
# f['participant'] = df['participant'].iloc[i]

# g = pd.DataFrame.from_dict(f, orient='index').T

# # new_df = pd.DataFrame(columns = ['iemg', 'mav', 'ssi', 'myopulse', 'wflen', 'diffvar', 'dasd',
# #        'willison', 'mean', 'min', 'max', 'rms', 'power', 'peak', 'p2p',
# #        'crest_factor', 'skew', 'kurtosis', 'form_factor', 'pulse_indicator',
# #        'max_f', 'sum_f', 'mean_f', 'var_f', 'peak_f', 'skew_f', 'kurtosis_f',
# #        'gesture', 'participant'])
# # new_df.append(e, ignore_index=True)
# # new_df
# e = e.append(g)
# e

In [144]:
new_df['participant'].unique()

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
       '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39',
       '4', '40', '41', '42', '43', '5', '6', '7', '8', '9'], dtype=object)

In [145]:
new_df.columns

Index(['crest_factor_F1', 'dasd_F1', 'diffvar_F1', 'form_factor_F1', 'iemg_F1',
       'kurtosis_F1', 'kurtosis_f_F1', 'mav_F1', 'max_F1', 'max_f_F1',
       ...
       'rms_W9', 'skew_W9', 'skew_f_W9', 'ssi_W9', 'sum_f_W9', 'var_f_W9',
       'wflen_W9', 'willison_W9', 'gesture', 'participant'],
      dtype='object', length=758)

In [146]:
new_df

crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0          7.091099  0.021834    0.000606    -6502.754507  365.456658   
0         13.324514  0.023852    0.000689     1352.897349  379.664639   
0          8.047954  0.016213    0.000326     1295.052394  296.823135   
0          8.459555  0.026572    0.000864    14453.068135  479.688214   
0          8.329011  0.026896    0.000901    11827.310277  464.350257   
..              ...       ...         ...             ...         ...   
0          7.771453  0.013208    0.000208     2599.892725  274.024844   
0          9.172642  0.019135    0.000429     1255.242161  385.695263   
0          5.923115  0.018533    0.000408     1713.228290  389.039490   
0          6.466362  0.015749    0.000292     -992.810528  319.503197   
0          6.331101  0.016365    0.000319     2571.088691  335.584187   

    kurtosis_F1  kurtosis_f_F1    mav_F1    max_F1  max_f_F1  ...    rms_W9  \
0      2.574033      85.547962  0.035689  0.047925  0.004600  ...  0.022588   
0     16.942218     329.114870  0.037077  0.057235  0.016957  ...  0.016172   
0      3.795827     134.751765  0.028987  0.039620  0.003721  ...  0.017039   
0      6.938354      98.832790  0.046845  0.068228  0.010985  ...  0.031982   
0      2.379207     116.412205  0.045347  0.060540  0.008721  ...  0.031134   
..          ...            ...       ...       ...       ...  ...       ...   
0      2.176596      28.888640  0.026760  0.035561  0.000668  ...  0.020526   
0      4.615531     133.237150  0.037666  0.051690  0.002916  ...  0.025825   
0      1.912226      22.613382  0.037992  0.050501  0.001450  ...  0.027460   
0      2.189195      21.864578  0.031201  0.041789  0.000820  ...  0.013359   
0      1.845409      28.544842  0.032772  0.043372  0.001164  ...  0.015422   

     skew_W9  skew_f_W9     ssi_W9  sum_f_W9      var_f_W9   wflen_W9  \
0  -0.148877   5.529415   5.224663  0.109574  2.901826e-10  69.944068   
0  -0.205427   9.332349   2.677940  0.077566  2.769772e-10  54.530919   
0  -0.204604   9.078430   2.973002  0.064458  1.426359e-10  57.815909   
0  -0.266818   5.067522  10.473811  0.131909  4.509337e-10  83.441138   
0  -0.092205   5.414199   9.925787  0.177516  9.577100e-10  94.393506   
..       ...        ...        ...       ...           ...        ...   
0  -0.293608   3.830298   4.314177  0.035283  1.966555e-11  40.970398   
0  -0.389927   4.200155   6.829604  0.076162  1.003953e-10  52.342457   
0  -0.321020   4.375813   7.721463  0.081006  1.125954e-10  59.843660   
0  -0.493375   3.832319   1.827333  0.062739  6.332731e-11  35.905471   
0  -0.457244   3.590272   2.435599  0.071311  7.882752e-11  40.497393   

    willison_W9  gesture  participant  
0          15.0       10            1  
0          23.0       10            1  
0          13.0       10            1  
0           0.0       10            1  
0           3.0       10            1  
..          ...      ...          ...  
0           2.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           0.0        9            9  
0           4.0        9            9  

[15351 rows x 758 columns]

In [153]:
df.reset_index(drop = True, inplace=True)

In [154]:
df.head(10)

session participant gesture trial  \
0       1           1      10     1   
1       1           1      10     2   
2       1           1      10     3   
3       1           1      10     4   
4       1           1      10     5   
5       1           1      10     6   
6       1           1      10     7   
7       1           1      11     1   
8       1           1      11     2   
9       1           1      11     3   

                                            filename  
0  E:\DS5500-project\data\gesture-recognition-and...  
1  E:\DS5500-project\data\gesture-recognition-and...  
2  E:\DS5500-project\data\gesture-recognition-and...  
3  E:\DS5500-project\data\gesture-recognition-and...  
4  E:\DS5500-project\data\gesture-recognition-and...  
5  E:\DS5500-project\data\gesture-recognition-and...  
6  E:\DS5500-project\data\gesture-recognition-and...  
7  E:\DS5500-project\data\gesture-recognition-and...  
8  E:\DS5500-project\data\gesture-recognition-and...  
9  E:\DS5500-project\data\gesture-recognition-and...

In [167]:
output_df = pd.concat([df.drop(columns=['participant', 'gesture']), new_df], axis = 1)

In [168]:
output_df

session trial                                           filename  \
0           1     1  E:\DS5500-project\data\gesture-recognition-and...   
1           1     2  E:\DS5500-project\data\gesture-recognition-and...   
2           1     3  E:\DS5500-project\data\gesture-recognition-and...   
3           1     4  E:\DS5500-project\data\gesture-recognition-and...   
4           1     5  E:\DS5500-project\data\gesture-recognition-and...   
...       ...   ...                                                ...   
15346       3     3  E:\DS5500-project\data\gesture-recognition-and...   
15347       3     4  E:\DS5500-project\data\gesture-recognition-and...   
15348       3     5  E:\DS5500-project\data\gesture-recognition-and...   
15349       3     6  E:\DS5500-project\data\gesture-recognition-and...   
15350       3     7  E:\DS5500-project\data\gesture-recognition-and...   

       crest_factor_F1   dasd_F1  diffvar_F1  form_factor_F1     iemg_F1  \
0             7.091099  0.021834    0.000606    -6502.754507  365.456658   
1            13.324514  0.023852    0.000689     1352.897349  379.664639   
2             8.047954  0.016213    0.000326     1295.052394  296.823135   
3             8.459555  0.026572    0.000864    14453.068135  479.688214   
4             8.329011  0.026896    0.000901    11827.310277  464.350257   
...                ...       ...         ...             ...         ...   
15346         7.771453  0.013208    0.000208     2599.892725  274.024844   
15347         9.172642  0.019135    0.000429     1255.242161  385.695263   
15348         5.923115  0.018533    0.000408     1713.228290  389.039490   
15349         6.466362  0.015749    0.000292     -992.810528  319.503197   
15350         6.331101  0.016365    0.000319     2571.088691  335.584187   

       kurtosis_F1  kurtosis_f_F1  ...    rms_W9   skew_W9  skew_f_W9  \
0         2.574033      85.547962  ...  0.022588 -0.148877   5.529415   
1        16.942218     329.114870  ...  0.016172 -0.205427   9.332349   
2         3.795827     134.751765  ...  0.017039 -0.204604   9.078430   
3         6.938354      98.832790  ...  0.031982 -0.266818   5.067522   
4         2.379207     116.412205  ...  0.031134 -0.092205   5.414199   
...            ...            ...  ...       ...       ...        ...   
15346     2.176596      28.888640  ...  0.020526 -0.293608   3.830298   
15347     4.615531     133.237150  ...  0.025825 -0.389927   4.200155   
15348     1.912226      22.613382  ...  0.027460 -0.321020   4.375813   
15349     2.189195      21.864578  ...  0.013359 -0.493375   3.832319   
15350     1.845409      28.544842  ...  0.015422 -0.457244   3.590272   

          ssi_W9  sum_f_W9      var_f_W9   wflen_W9  willison_W9  gesture  \
0       5.224663  0.109574  2.901826e-10  69.944068         15.0       10   
1       2.677940  0.077566  2.769772e-10  54.530919         23.0       10   
2       2.973002  0.064458  1.426359e-10  57.815909         13.0       10   
3      10.473811  0.131909  4.509337e-10  83.441138          0.0       10   
4       9.925787  0.177516  9.577100e-10  94.393506          3.0       10   
...          ...       ...           ...        ...          ...      ...   
15346   4.314177  0.035283  1.966555e-11  40.970398          2.0        9   
15347   6.829604  0.076162  1.003953e-10  52.342457          0.0        9   
15348   7.721463  0.081006  1.125954e-10  59.843660          0.0        9   
15349   1.827333  0.062739  6.332731e-11  35.905471          0.0        9   
15350   2.435599  0.071311  7.882752e-11  40.497393          4.0        9   

       participant  
0                1  
1                1  
2                1  
3                1  
4                1  
...            ...  
15346            9  
15347            9  
15348            9  
15349            9  
15350            9  

[15351 rows x 761 columns]

In [169]:
output_df.to_csv(base_path+"features_v2.csv", index = False)

In [170]:
output_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15351 entries, 0 to 15350
Columns: 761 entries, session to participant
dtypes: float64(756), object(5)
memory usage: 89.1+ MB
