In [111]:
import torch

import os
import re
import sys

In [112]:
import time

In [113]:
import importlib

In [114]:
from torch.utils.data import DataLoader

In [115]:
from feature_ops import *

In [116]:
importlib.reload(data_utils)

<module 'data_utils' from 'E:\\DS5500-project\\DL\\data_utils.py'>

In [117]:
import data_utils
from data_utils import FileDataset, Ops

In [5]:
session1 = os.path.abspath("../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/Session1/")
session2 = os.path.abspath("../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/Session2/")
session3 = os.path.abspath("../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/Session3/")

In [6]:
session_1_folder = [os.path.join(session1, f) for f in os.listdir(session1)]

In [7]:
session_1_folder

['E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant1',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant10',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant11',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant12',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant13',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant14',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant15',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\se

In [37]:
participants = [str(i+1) for i in range(25)]

In [38]:
participants

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25']

In [39]:
get_part_pat = ".+[a-z](\d+)$"

In [40]:
train_ds_folders = []

In [41]:
for f in session_1_folder:
    m = re.match(get_part_pat, f)
    if m.group(1) in participants:
        train_ds_folders.append(f)

In [42]:
train_ds_folders

['E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant1',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant10',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant11',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant12',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant13',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant14',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant15',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\se

In [43]:
ops = Ops([
    mean, std, 
    min_feature,
    max_feature, peak,
    mav, form_factor,
    pulse_indicator, mean_f,
    std_f, max_f, min_f
])

In [118]:
#This must be a folder
train_ds = FileDataset(folder_list=train_ds_folders, transforms=ops)

In [119]:
train_dl = DataLoader(train_ds, batch_size=32, shuffle=True) 

In [48]:
start = time.time()
c = 0
for data, label in train_dl:
#     print(data.shape)
#     print(label.shape)
    print(type(label))
    c+=1
    
print(time.time() - start)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'tor

## Test Machine Learning Model

In [163]:
importlib.reload(simple_nets)

<module 'simple_nets' from 'E:\\DS5500-project\\DL\\simple_nets.py'>

In [164]:
import simple_nets
from simple_nets import SimpleFCNet

In [165]:
from torchsummary import summary

In [166]:
label

tensor([ 6, 16, 10,  2,  9, 17,  3, 15,  3, 11,  5, 11,  7,  4,  3,  9,  5, 13,
        14,  9,  1, 10,  6,  9, 15,  7,  7,  5, 10,  7, 15])

In [167]:
data.shape[1]

336

In [171]:
model = SimpleFCNet(data.shape[1], 18, apply_log_softmax=False)

In [172]:
summary(model,(32, data.shape[1]))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1              [-1, 32, 128]          43,136
            Linear-2              [-1, 32, 256]          33,024
            Linear-3              [-1, 32, 128]          32,896
            Linear-4               [-1, 32, 18]           2,322
Total params: 111,378
Trainable params: 111,378
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.04
Forward/backward pass size (MB): 0.13
Params size (MB): 0.42
Estimated Total Size (MB): 0.60
----------------------------------------------------------------


In [173]:
criterion = torch.nn.CrossEntropyLoss()

In [174]:
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

In [175]:
val_interval = 2
num_epochs = 10

In [176]:
train_losses = []
val_losses = []
accuracies = []

In [178]:
t = torch.randint(0, 18, (32,))
i = torch.rand((32, 18))

In [179]:
t

tensor([14,  9, 14, 12,  0,  5,  4, 15, 10, 10,  8,  4, 16, 10,  8, 16,  5,  6,
        10, 11, 13, 17,  6,  8, 11, 17,  1,  9, 12,  7,  3, 11])

In [180]:
i.shap

tensor([[0.5634, 0.4424, 0.3335, 0.6961, 0.4030, 0.6523, 0.6394, 0.0119, 0.0212,
         0.2908, 0.7921, 0.0611, 0.8486, 0.1077, 0.2228, 0.3324, 0.8768, 0.6962],
        [0.1364, 0.8546, 0.8697, 0.9110, 0.6730, 0.6388, 0.9962, 0.4409, 0.1529,
         0.6657, 0.2910, 0.9462, 0.9894, 0.2245, 0.2063, 0.7163, 0.3391, 0.2776],
        [0.5293, 0.6261, 0.4515, 0.4327, 0.5325, 0.2387, 0.4097, 0.4876, 0.7898,
         0.2573, 0.6175, 0.6446, 0.3177, 0.8176, 0.0597, 0.7934, 0.5036, 0.8469],
        [0.7137, 0.7098, 0.0588, 0.7573, 0.9744, 0.9018, 0.2214, 0.9274, 0.4825,
         0.3150, 0.0689, 0.2944, 0.4144, 0.5914, 0.1007, 0.2358, 0.5028, 0.3071],
        [0.9147, 0.4892, 0.4428, 0.9876, 0.6504, 0.3012, 0.6005, 0.7878, 0.1438,
         0.2832, 0.9861, 0.7665, 0.8567, 0.4062, 0.1238, 0.1435, 0.0246, 0.5131],
        [0.2190, 0.2208, 0.5149, 0.2668, 0.2947, 0.1651, 0.3186, 0.8440, 0.3879,
         0.0280, 0.7469, 0.8727, 0.0375, 0.2041, 0.4447, 0.6701, 0.1127, 0.4831],
        [0.1530, 0.800

In [151]:
from tqdm import tqdm

In [153]:
for epoch in range(1, num_epochs + 1):
    model.train()
    total_train_loss = 0
    print(f"------------Epoch {epoch}-------------")
    for batch_data, batch_target in tqdm(train_dl):
        optimizer.zero_grad()
        batch_target = batch_target - 1
        predictions = model(batch_data)
        loss = criterion(predictions, batch_target)
        loss.backward()
        optimizer.step()
        total_train_loss += loss.item()

    average_train_loss = total_train_loss / len(train_dl)
    train_losses.append(average_train_loss)

    if epoch % val_interval == 0:
        model.eval()
        total_val_loss = 0
        all_preds = torch.tensor([])
        all_batch = torch.tensor([])
        with torch.no_grad():
            for batch_data, batch_target in train_dl:
                batch_target = batch_target - 1
                predictions = model(batch_data)
                int_pred = torch.argmax(predictions, dim = 1)
                all_preds = torch.hstack([all_preds, int_pred])
                all_batch = torch.hstack([all_batch, batch_target])
                loss = criterion(predictions, batch_target)
                total_val_loss += loss.item()
            accuracies.append(sum(all_batch==all_preds) / len(all_batch)) 

        average_val_loss = total_val_loss / len(train_dl)
        val_losses.append(average_val_loss)

    print(f'Epoch [{epoch}/{num_epochs}] - Train Loss: {average_train_loss:.4f}')

------------Epoch 1-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [02:57<00:00,  1.91s/it]


Epoch [1/10] - Train Loss: 2075825633310.1458
------------Epoch 2-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:13<00:00,  2.08s/it]


Epoch [2/10] - Train Loss: 6.2151
------------Epoch 3-------------


  8%|██████▏                                                                            | 7/93 [00:16<03:20,  2.34s/it]


KeyboardInterrupt: 

In [154]:
accuracies

[tensor(0.0602)]

In [155]:
all_preds

tensor([3., 3., 3.,  ..., 3., 3., 3.])

In [69]:
batch_target

tensor([ 6,  5, 16,  0,  2,  4, 10,  6,  2,  4, 11,  7, 14,  7, 15, 12, 15,  6,
        14,  7, 16, 13,  3,  3, 10,  7,  7, 16,  1, 16, 13,  5])

In [70]:
model.num_input

336

In [110]:
batch_target.dtype

torch.int64

In [109]:
model.l1.weight.dtype

torch.float32

In [139]:
torch.argmax(predictions, dim = 1)

tensor([ 2,  2,  2, 12,  2,  2,  3,  2,  2,  2,  3,  2,  2,  2,  2,  3,  3,  2,
         2,  2,  2,  5,  2,  2,  2,  2,  2,  3,  2,  2,  2])