In [111]:
import torch

import os
import re
import sys

In [112]:
import time

In [113]:
import importlib

In [114]:
from torch.utils.data import DataLoader

In [115]:
from feature_ops import *

In [116]:
importlib.reload(data_utils)

<module 'data_utils' from 'E:\\DS5500-project\\DL\\data_utils.py'>

In [117]:
import data_utils
from data_utils import FileDataset, Ops

In [5]:
session1 = os.path.abspath("../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/Session1/")
session2 = os.path.abspath("../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/Session2/")
session3 = os.path.abspath("../data/gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2/Session3/")

In [6]:
session_1_folder = [os.path.join(session1, f) for f in os.listdir(session1)]

In [7]:
session_1_folder

['E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant1',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant10',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant11',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant12',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant13',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant14',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant15',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\se

In [37]:
participants = [str(i+1) for i in range(25)]

In [38]:
participants

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25']

In [39]:
get_part_pat = ".+[a-z](\d+)$"

In [40]:
train_ds_folders = []

In [41]:
for f in session_1_folder:
    m = re.match(get_part_pat, f)
    if m.group(1) in participants:
        train_ds_folders.append(f)

In [42]:
train_ds_folders

['E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant1',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant10',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant11',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant12',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant13',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant14',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\session1_participant15',
 'E:\\DS5500-project\\data\\gesture-recognition-and-biometrics-electromyogram-grabmyo-1.0.2\\Session1\\se

In [43]:
ops = Ops([
    mean, std, 
    min_feature,
    max_feature, peak,
    mav, form_factor,
    pulse_indicator, mean_f,
    std_f, max_f, min_f
])

In [118]:
#This must be a folder
train_ds = FileDataset(folder_list=train_ds_folders, transforms=ops)

In [119]:
train_dl = DataLoader(train_ds, batch_size=32, shuffle=True) 

In [48]:
start = time.time()
c = 0
for data, label in train_dl:
#     print(data.shape)
#     print(label.shape)
    print(type(label))
    c+=1
    
print(time.time() - start)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'tor

## Test Machine Learning Model

In [163]:
importlib.reload(simple_nets)

<module 'simple_nets' from 'E:\\DS5500-project\\DL\\simple_nets.py'>

In [164]:
import simple_nets
from simple_nets import SimpleFCNet

In [165]:
from torchsummary import summary

In [166]:
label

tensor([ 6, 16, 10,  2,  9, 17,  3, 15,  3, 11,  5, 11,  7,  4,  3,  9,  5, 13,
        14,  9,  1, 10,  6,  9, 15,  7,  7,  5, 10,  7, 15])

In [167]:
data.shape[1]

336

In [171]:
model = SimpleFCNet(data.shape[1], 18, apply_log_softmax=False)

In [172]:
summary(model,(32, data.shape[1]))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1              [-1, 32, 128]          43,136
            Linear-2              [-1, 32, 256]          33,024
            Linear-3              [-1, 32, 128]          32,896
            Linear-4               [-1, 32, 18]           2,322
Total params: 111,378
Trainable params: 111,378
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.04
Forward/backward pass size (MB): 0.13
Params size (MB): 0.42
Estimated Total Size (MB): 0.60
----------------------------------------------------------------


In [173]:
criterion = torch.nn.CrossEntropyLoss()

In [174]:
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

In [175]:
val_interval = 2
num_epochs = 10

In [176]:
train_losses = []
val_losses = []
accuracies = []

In [178]:
t = torch.randint(0, 18, (32,))
i = torch.rand((32, 18))

In [179]:
t

tensor([14,  9, 14, 12,  0,  5,  4, 15, 10, 10,  8,  4, 16, 10,  8, 16,  5,  6,
        10, 11, 13, 17,  6,  8, 11, 17,  1,  9, 12,  7,  3, 11])

In [181]:
i.shape

torch.Size([32, 18])

In [185]:
l = criterion(i, batch_target)

In [188]:
batch_target 

tensor([ 7, 15, 16, 11, 14, 12,  2,  1,  4, 10, 12,  2,  7, 13,  9,  1,  1,  8,
         1, 12, 15,  2,  9, 13, 13, 10, 14,  6,  3, 15,  9,  3])

In [189]:
l

tensor(2.9800)

In [190]:
from tqdm import tqdm

In [191]:
for epoch in range(1, num_epochs + 1):
    model.train()
    total_train_loss = 0
    print(f"------------Epoch {epoch}-------------")
    for batch_data, batch_target in tqdm(train_dl):
        optimizer.zero_grad()
        batch_target = batch_target - 1
        predictions = model(batch_data)
        loss = criterion(predictions, batch_target)
        loss.backward()
        optimizer.step()
        total_train_loss += loss.item()

    average_train_loss = total_train_loss / len(train_dl)
    train_losses.append(average_train_loss)

    if epoch % val_interval == 0:
        model.eval()
        total_val_loss = 0
        all_preds = torch.tensor([])
        all_batch = torch.tensor([])
        with torch.no_grad():
            for batch_data, batch_target in train_dl:
                batch_target = batch_target - 1
                predictions = model(batch_data)
                int_pred = torch.argmax(predictions, dim = 1)
                all_preds = torch.hstack([all_preds, int_pred])
                all_batch = torch.hstack([all_batch, batch_target])
                loss = criterion(predictions, batch_target)
                total_val_loss += loss.item()
            accuracies.append(sum(all_batch==all_preds) / len(all_batch)) 

        average_val_loss = total_val_loss / len(train_dl)
        val_losses.append(average_val_loss)

    print(f'Epoch [{epoch}/{num_epochs}] - Train Loss: {average_train_loss:.4f}')

------------Epoch 1-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:01<00:00,  1.95s/it]


Epoch [1/10] - Train Loss: 1512.0547
------------Epoch 2-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:14<00:00,  2.09s/it]


Epoch [2/10] - Train Loss: 2.8951
------------Epoch 3-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:10<00:00,  2.05s/it]


Epoch [3/10] - Train Loss: 2.8433
------------Epoch 4-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:07<00:00,  2.02s/it]


Epoch [4/10] - Train Loss: 2.8402
------------Epoch 5-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:08<00:00,  2.02s/it]


Epoch [5/10] - Train Loss: 2.8387
------------Epoch 6-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:04<00:00,  1.98s/it]


Epoch [6/10] - Train Loss: 2.8374
------------Epoch 7-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [02:50<00:00,  1.83s/it]


Epoch [7/10] - Train Loss: 2.8371
------------Epoch 8-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [02:36<00:00,  1.68s/it]


Epoch [8/10] - Train Loss: 2.8364
------------Epoch 9-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:05<00:00,  1.99s/it]


Epoch [9/10] - Train Loss: 2.8360
------------Epoch 10-------------


100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [03:04<00:00,  1.98s/it]


Epoch [10/10] - Train Loss: 2.8359


In [192]:
accuracies

[tensor(0.0595),
 tensor(0.0588),
 tensor(0.0585),
 tensor(0.0602),
 tensor(0.0588)]

In [155]:
all_preds

tensor([3., 3., 3.,  ..., 3., 3., 3.])

In [69]:
batch_target

tensor([ 6,  5, 16,  0,  2,  4, 10,  6,  2,  4, 11,  7, 14,  7, 15, 12, 15,  6,
        14,  7, 16, 13,  3,  3, 10,  7,  7, 16,  1, 16, 13,  5])

In [70]:
model.num_input

336

In [110]:
batch_target.dtype

torch.int64

In [109]:
model.l1.weight.dtype

torch.float32

In [139]:
torch.argmax(predictions, dim = 1)

tensor([ 2,  2,  2, 12,  2,  2,  3,  2,  2,  2,  3,  2,  2,  2,  2,  3,  3,  2,
         2,  2,  2,  5,  2,  2,  2,  2,  2,  3,  2,  2,  2])